### ISSUE TITLE
Clean way to enable/disable features at runtime without modifying the profile asset?

### ISSUE THREAD

**Issue by billowper** [Unity-Technologies/PostProcessing#11]
Feels like a potential shortcoming of this new system, without public access to the PostProcessingComponents via PostProcessingBehaviour. Have resorted to instantiating the profile asset when I want to make modifications at runtime.

**Comment by LKGames** [comment]
You can edit the profile without creating new instances of it:

`PostProcessingProfile fxProfile = GetComponent<PostProcessingBehaviour>().profile;
fxProfile.screenSpaceReflection.enabled = false;`

I wasn't able to access certain parts of the profile though (such as the color grading options, for example).

**Comment by billowper** [comment]
Presumably this will mean changing data serialized on the .asset itself, at runtime? That's what I'd want to avoid (in previous version of the stack you'd just enable/disable the MonoBehaviours for a given effect.)

The use case is a simple options system, where the player can toggle features in the stack. Changing data in assets doesn't seem like an optimal way to do this...

**Comment by Chman** [comment]
Changing the asset at runtime is one way of doing it and it will work fine, but it's not optimal as you said.

Another way would be to keep an internal copy of the asset and modify it instead (so that the profile asset becomes the "default" state, or "initial state").

Here's a simple pulsating vignette effect using this technique:

```
using UnityEngine;
using UnityEngine.PostProcessing;

[RequireComponent(typeof(PostProcessingBehaviour))]
public class AnimationDemo : MonoBehaviour
{
    PostProcessingProfile m_Profile;

    void OnEnable()
    {
        var behaviour = GetComponent<PostProcessingBehaviour>();

        if (behaviour.profile == null)
        {
            enabled = false;
            return;
        }

        m_Profile = Instantiate(behaviour.profile);
        behaviour.profile = m_Profile;
    }

    void Update()
    {
        var vignette = m_Profile.vignette.settings;
        vignette.smoothness = Mathf.Abs(Mathf.Sin(Time.realtimeSinceStartup) * 0.99f) + 0.01f;
        m_Profile.vignette.settings = vignette;
    }
}
```

You'll probably want the internal profile copy to be handled by a manager if you need more complex setups but that's the general idea.

We're aware that it's not the most straightforward nor efficient way of animating profile values and we're currently working on a more flexible solution.

**Comment by cameronoltmann** [comment]
While it would be nice if this were a bit simpler, I've got this set up and it's working pretty well.  As an added bonus, if you have multiple cameras with the same profile assigned, you can change post processing settings on both with a single call.  Very slick.

**Comment by Kink3d** [comment]
This information has now been moved to a wiki page [here](https://github.com/Unity-Technologies/PostProcessing/wiki/Runtime-Post-Processing-Modification). Closing.
