### ISSUE TITLE
Forward rendering + Depth Only Clear Flag + Ambient Occlusion = White Screen

### ISSUE THREAD

**Issue by JTown-** [Unity-Technologies/PostProcessing#119]
Same thing happens with motion blur (after hitting play). 

I'm running 5.5.0f3 on mac

**Comment by Kink3d** [comment]
Are you using MSAA? We have a very wide known failure case for MSAA + multi camera setups in 5.5. With Ambient Occlusion enabled it results in essentially returning the AO debug view. There is a major camera refactor in 5.6 that should fix this (thoroughly tested internally) however the fix is way too big to backport to 5.5.

**Comment by JTown-** [comment]
Hmm, it seems to happen with or without MSAA. My test scene just has two cameras -- one clearing to skybox, one clearing to depth, both set to forward rendering. But now when I check, even the skybox cam goes white with motion blur and ambient occlusion... pretty sure it was fine yesterday. I've noticed other times where things seem inconsistent. 

But the 5.6 fix sounds nice -- there a link with more details on that? Have some other issues with my camera setup unrelated to this post process stack, so I'm curious what all it fixes.

**Comment by Kink3d** [comment]
Ok strange, could you provide a small reproduction project for me to look at?

**Comment by Kink3d** [comment]
Just looked at this and yes it does reproduce in forward rendering path without MSAA. It is indeed fixed in 5.6 (in my tests), however as I said before, this wont get backported to 5.5 im afraid.
