### ISSUE TITLE
Bloom flickering

### ISSUE THREAD

**Issue by kakins** [Unity-Technologies/PostProcessing#121]
Note that the older version of bloom as part of the Standard Assets package does not exhibit a flickering behavior.

I have a trail renderer attached to a moving game object.  The trail renders a material that facilitates the bloom effect.  However I noticed whenever the trail is moving, the bloom effect seems to be 'wavy' or 'flickering'.  I tried clicking the Anti Flicker option and it does not seem to help.

Here is a screenshot representing the behavior.  On the right you can see the waviness of the bloom effect.  Is there some other setting that may be causing this?  I've tried disabling all other image effects aside from bloom, to no avail.
![screenshot 7](https://cloud.githubusercontent.com/assets/14915247/24022612/9ab42500-0a75-11e7-8c7f-068b81837055.png)

I also notice this flickering behavior on the bloomed object whenever I navigate the camera in the Scene view.

**Comment by nestg** [comment]
I have same problem, i hope that this will be fix in next release.

**Comment by sasa42** [comment]
Hello. Is there some work or progress.
Every bloom is flickering. 
Tried out all configurations.
You can easily compare with yebis for unity.
All scenes in every configuration show same behavior.
PostProcessingStack Bloom. Flickering.
Yebis Bloom. Stabil.
Probably its more an bug as an enhancement?

**Comment by snlehton** [comment]
I'm running Unity 5.6.1p1 and v2 post processing stack. I tried replacing the bloom in Sonic Ether's Natural Bloom andDirty Lens demo scene with Unity post processing, and the result is flickering insanely.

However, just having some post processing (like color grading) causes flickering also on SENBDL effect. If I disable Unity's post processing stack, everything is smooth.  It seems there is something inherently wrong with Unity 5.6.1p1 and Unity post processing stack.

**Comment by Kink3d** [comment]
Hi,

The problem is with the actual bloom implementation. Fixing it properly essentially requires a total rewrite of the effect. This has been done for V2 and fixes flickering in our test cases, however it will not be backported to V1.

For the record using external bloom solutions with the stack (V1) will still result in flickering due to where effects should take place in a proper post-processing chain. In the V1 stack it is not possible (without heavy modification) to apply Bloom at the correct point in the chain, resulting in flickering.

In V2 stack it will be possible to use any external Bloom solution alongside our stack if you wish, provided that that Bloom is modified to fit within our framework (we hope most Asset Store publishers will see the value in this).

Thanks.

**Comment by mmalek06** [comment]
It doesn't seem the problem is entirely fixed in v2. In my case if I use a baked spotlight then in the place of it's origin I can see white bulbs flashing in random positions. This doesn't happen when using point light.

**Comment by kakins** [comment]
I think I second the fact that this doesn't seem to be resolved with the latest version as 10/1/2017.  I still notice the flickering effect in the example given in the original screenshot for this issue.  There are other issues with it now as well in V2, but I'll save those for a topic.  Anyhow, it seems strange that I can still the older Standard Assets bloom effect and I experience no flickering, the effect works perfectly..
