### ISSUE TITLE
Questions about the PostProcessing Stack

### ISSUE THREAD

**Issue by semaphorelab** [Unity-Technologies/PostProcessing#129]
- One common feature in screen space AO assets nowadays is supporting color bleeding (simulated) as can be seen here:
https://d2ujflorbtfzji.cloudfront.n...9f91aa-6866-4dcc-b661-91c44589e511_scaled.jpg
Are there any plans to add such a feature? It adds a lot to the look of the scene from our experiments.

- Any plans to add sunshafts as they were in the old image effects?

- Is it possible to add a "target object" for DOF so that we can focus on that object while everything else is blurred? A common example would be aiming down the sights. This will allow us to implement adaptive DOF in gameplay.

**Comment by Chman** [comment]
- No plan for SSDO / AO color bleeding.
- Sunshafts will come at some point, not just yet.
- Two reasons we don't have that field right now: first, because the configuration is asset based and you can't reference scene objects in an asset (hard limitation). Second, because it doesn't make much sense. Focusing on a transform doesn't make any sense unless it's straight in front of the camera (because you focus in a straight line). What happens if the object is on the side of the screen? What's the correct distance in this case? What happens if the object is behind the camera? So you'll have to rely on "distance to camera". Eventually we'll have something to make it easier to tweak (another thing on the roadmap). But in the meantime, you'll have to do auto-focus via scripting (a raycast/distance + progressive interpolation should be enough to give a nice, smooth, auto-focus effect).
