### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#152]
![default](https://cloud.githubusercontent.com/assets/18855621/24987787/5f4d929c-2034-11e7-9a02-8d6263603463.JPG)

**Comment by Kink3d** [comment]
Hi,

Please try to be more helpful when providing bug reports. The title and contents of this report are of no use when debugging a potential issue with SSR. Also, the report template is there for a reason and it being correctly filled in is vital to us.

Furthermore I have no idea what your SSR setup is here and therefore cannot discern whether this is an issue or not. 

I am closing this issue. If you wish to open another report with helpful contents so that we can try to assist you then please do so.
