### ISSUE TITLE
SSR wrong reflection of character on ground

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#153]
##### What happened?
Look the reflection of right hand of character, it should not be there:
![ssr1](https://cloud.githubusercontent.com/assets/18855621/25007935/b1cac854-2094-11e7-88cb-cccc5ccdb551.png)

And I just find reflection flickers in edges of models:
![ssr2](https://cloud.githubusercontent.com/assets/18855621/25008176/839406c0-2095-11e7-8f53-b50c48d1f18f.png)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.0f3, Win10 pro 1607,  target platform windows.

Sorry about previous report I forgot to fill title and details, hope this helpful.

**Comment by Kink3d** [comment]
Hi,

I have been able to reproduce similar tracing problems. These are intrinsic to the raymarching algorithm used by the this version of SSR and therefore I'm afraid that this will not get fixed in this iteration of the effect. However, we are working on a new SSR implementation (with a new raymarching algorithm) which should be more accurate.
