### ISSUE TITLE
RenderTexture's Alpha has noise.

### ISSUE THREAD

**Issue by fine-matsumoto** [Unity-Technologies/PostProcessing#159]
Always thank you for a wonderful job!

Noise is added to alpha when RenderTexture is generated with Camera which checked Antialiasing of PostProcessing.

![postprocess_anti_alpha_error](https://cloud.githubusercontent.com/assets/11779621/25217973/01a32db8-25e4-11e7-8db8-8c9711f3499c.png)

--
OS : windows7
GPU : GeForceGTX960 with 378.66 drivers
Unity : 5.5.2f1

**Comment by Kink3d** [comment]
Hi,

Good catch. This was because FXX and TAA use the alpha channel to store various data. This is fixed in master now as we write 1 back into the alpha channel at the end of the Uber shader. Please update to latest :)

It should be noted that when using TAA this problem will require using another effect from Uber shader for the fix (anything other than SO, SSR, Motion Blur).

Thanks for bringing this to our attention.

**Comment by fine-matsumoto** [comment]
Thank you for the reply.

I deleted all PostProcessing folders.
got the latest version from AssetStore.

But the result did not change. . .
prepared a new project and experimented with Cube, but the edges were passed through

![2017-04-21_09h17_05](https://cloud.githubusercontent.com/assets/11779621/25257527/825fec2c-2673-11e7-8baa-82c843db4ae8.png)
![rendertexturealpha](https://cloud.githubusercontent.com/assets/11779621/25257993/1ef0c004-2677-11e7-8934-07648bb0e3e1.gif)

**Comment by Kink3d** [comment]
Hi,

This fix is not currently on the Asset Store. It will be submitted today for approval but might take a few days. Please get the fix by downloading the latest directly from this Github repository.

Thanks

**Comment by fine-matsumoto** [comment]
Alpha noises are gone, But Alpha is gone
Is this a specification?
If so, you have to use another PostEffect...
