### ISSUE TITLE
Postprocessing crashes game on Honor 7 Lite (Android)

### ISSUE THREAD

**Issue by tanlah** [Unity-Technologies/PostProcessing#163]
##### What happened?
When postprocessing is attached to camera in our main scene, the game crashes after title screen.
Has only happened on Honor 7 lite, other devices work fine.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6 tested apk builds from both Linux and Windows.
Device Honor 7 Lite, Android 6.0

No real stacktrace or decent error message visible, this is the last log message and it doesn't appear when postprocessing is removed.

```
04-22 17:08:23.186   453   453 E DEBUG   : AM write failed: Broken pipe
```

There's also this message which may be related.

```
04-22 17:08:18.390  7938  7958 E Unity   : -------- GLSL link error:  The number of vertex shader storage blocks (1) is greater than the maximum number allowed (0).
```

**Comment by Kink3d** [comment]
Hi, sorry for the late reply.

This seems to be due to Eye Adaptation. This effect is not supported on that hardware. However the effect should fail silently. Could you please try `SystemInfo.supportsComputeShaders` on that device? We use this to check for Eye Adaptation support. If it returns true on your device we may need to look at more options for safety in these situations.

Thanks

**Comment by Kink3d** [comment]
Closed due to inactivity
