### ISSUE TITLE
Adding custom effects into the stack

### ISSUE THREAD

**Issue by CaiusEugene** [Unity-Technologies/PostProcessing#164]
I was wondering if there are any plans to allow a developers to add custom shaders into the stack, for example I wanted to desaturate the color in my scene, currently I'm using an image effect shader I've written along side the PPS. I'd like to be able to add this into the stack to keep all the logic in one place.

Thanks, C.

**Comment by Kink3d** [comment]
Hi,

Yes we are working on a solution for this. Unfortunately I cant really say anymore than that at this point as its under heavy development but it is coming :)

Will leave this open so others can see the response.

Thanks

**Comment by ssameng** [comment]
Glad to hear this is being worked on!

Is there a good method currently to get a HDR output from the stack?

**Comment by Chman** [comment]
> I think adding effects right now can't really be done due to the stack ouputting LDR.

And you would be right, the stack outputs to LDR because of some effects (Color grading & tonemapping output LDR data. Grain & dithering need to be applied in LDR...).

> But of course ideally we will be able to "insert" our own effects in the middle of the stack

Yep, that's exactly the plan :) We're adding a few "injection points" for custom effects.

**Comment by ssameng** [comment]
Nice! I'm excited for the "injection points" but I'm a little worried that modifications will have to be done to existing effects to be able to inject them. 

If this is the case, would it be possible to have the stack output HDR if those latter effects (tonemapping, grading, grain) aren't enabled?

If the stack were able to spit out HDR, this issue can be somewhat sidestepped as we can just do regular daisy chaining with the stack

**Comment by Chman** [comment]
> but I'm a little worried that modifications will have to be done to existing effects to be able to inject them.

That's unavoidable. Effects will have to be ported over to the new framework if you want them to fit into the stack and enjoy all the cool new things you'll be able to do with the updated framework & tools. Generally speaking it should be fairly easy though.

Do note that custom user-effects won't require any modification to the framework source code, we're working toward a very extensible system.

> If this is the case, would it be possible to have the stack output HDR if those latter effects (tonemapping, grading, grain) aren't enabled?

If you inject before dithering happens, that's possible. Else, unless you execute your effects before the stack, no. Final-pass dithering is currently hard-coded into the new framework because it's cheap and generally mandatory for good default visual results, especially with HDR.

It's hard to make it fit all possible use-cases in a truly generic way while keeping it efficient (plus we have a few engine/workflow related constrains to take into account), so if you really need to customize the stack to your specific needs... It'll be open-source, fork it ;)

We'll communicate more about all of this once we reach the beta stages.

**Comment by Kink3d** [comment]
With beta release of V2 we now support custom user effects. Closing this :)

**Comment by unity3d-kr** [comment]
https://github.com/Unity-Technologies/PostProcessing/wiki/Writing-Custom-Effects
