### ISSUE TITLE
Motion Blur  - waste more resources than needed

### ISSUE THREAD

**Issue by fdsagizi** [Unity-Technologies/PostProcessing#166]
Hi guys, motion blur in unity and poss procces - waste more resources than needed... 
**First problem** is texture formats, best format for mobile platform is RGBA8 but you use

`RenderTextureFormat m_VectorRTFormat = RenderTextureFormat.RGHalf;   
RenderTextureFormat m_PackedRTFormat = RenderTextureFormat.ARGB2101010;
m_PackedRTFormat = RenderTextureFormat.ARGB32; // If 2:10:10:10 isn't supported, use ARGB32 instead.`
           
Why you just not use RGBA8 for it? it really fast, and have best performances and good result! 
you can see it in my game, witch i made on my our game engine. And i just use RGBA8 for motion vectors. 

Motion Blur in action: https://youtu.be/hxYz9H52Brw?t=14m48s
Game it self: http://store.steampowered.com/app/352170/

And  even work fine on iOS, and required only 3-5% of GPU
AppStore you can just download it free and test! https://itunes.apple.com/ru/app/madout-fire/id993608794?mt=8

**Second problem** is - required additional Depth pass. I know it Unity3d architecture, but its still expensive for Mobile. Why not allow use back buffer directly - without draw second time?

**Comment by Chman** [comment]
**First problem:** What you call `RGBA8` is `ARGB32` (unless you really meant using a 2 bit-per-channel texture format, which doesn't exist and would have atrocious precision). `RGHalf` takes the same amount of space in memory and is used to keep good enough precision for the TileMax filtering passes. Of course, feel free to change it to `ARGB32` if you think it's enough for your use case, although I don't really see why you'd use a 4-channels texture for motion vectors, you'd essentially be losing precision and wasting space for two unused channels. Note that Unity uses `RGHalf` internally for motion vectors.

**Second problem:** Motion vectors require depth information, so the depth pass is already available and this is a non-issue. Unless I misunderstood what you said.

**Comment by fdsagizi** [comment]
**First**: may be i **wrong**, but when i test RGBA32 ( 8 bit per chanel ) vs RGHalf  on mobile 3 ears ago - RGBA32 was faster. 

**Second**: When you use Forward Render, and enable Depth Pass, draw calls grow on x2 times. And this really beat on performances... And i don't understand why not use camera depth buffer directly - without additional pass, like in Deffered Render?

**Comment by despoke** [comment]
On some (older) mobile hardware, sampling to floating point texture is slower than sampling to discrete textures (like rgba32), even for the same memroy footprint. This is because the given hardware does not have hardware support for full floating point filtering. That's probably what fdsagizi has experienced.

Depth buffer problem: as i recall, because not all platforms support sampling the depth buffer, unity sometimes chooses to render depth into a separate color render-target. This is why draw call is doubled too.

**Comment by Kink3d** [comment]
Hey,

Did some asking around and found out theres a few reasons why we do a separate depth pass in forward. The take home however is that this is because systems that use it have done for a long time and were never updated to more modern techniques.

1) Dynamic batching. Transforms vertices on the CPU and you cant have "multipass" rendering with the same depth buffer.

2) Directional shadow map has to be calculated before any object is drawn, this requires a depth buffer.

3) Soft particles.

Hopefully that helps.
