### ISSUE TITLE
Transparent materials present wrong DOF

### ISSUE THREAD

**Issue by nestg** [Unity-Technologies/PostProcessing#167]
Well is a very basic problem, nothing special in scene, i use standard shader in transparent (cutout same issue) mode, the stick of the flag have correct DOF but the flag is wrong, thanks.

![sin titulo](https://cloud.githubusercontent.com/assets/17572350/25407755/2466d2dc-29d1-11e7-9b78-84518bc6ad85.png)

Unity 5.6f03p2, last postprocessing stack version, forward rendering, Windows 7, Intel CPU and Nvidia GPU.

**Comment by Kink3d** [comment]
Hi,

With transparent materials this is the expected behaviour. As they dont write to the depth buffer and DoF will blur according to the depth value of a given pixel the blurring will be based on the distance of what did draw depth for that pixel (in this case the skybox).

With cutout materials however this shouldn't be the case as they do write to the depth buffer. I just tested this in a simple case and it works as expected in latest master.

There may be something wrong with your setup if cutout objects arent blurring correctly. If you provide a reproduction project we will look at it for you.

Thanks

**Comment by nestg** [comment]
Hi, i check the shader and is the Standard shader but customized for double sided rendering, when update the standard shader to last version and set mode to cutout the problem is fixed, you can close the issue, thank you very much.
