### ISSUE TITLE
Feature Request: Volumetric Atmospheric solutions

### ISSUE THREAD

**Issue by tdbe** [Unity-Technologies/PostProcessing#171]
It would be absolutely wonderful if you also assembled together into this toolset the various atmospheric scattering, volumetric fog, god rays solutions that unity&community has already had to some extent over many years. Because they are all now officially deprecated and it's as if we're downgraded. 
	
Thanks a bunch! I know you guys are working as effectively as possible and release the most production-dependable impactful solutions and relieve or frustrations!

**Comment by pavelkouril** [comment]
>  Because they are all now officially deprecated and it's as if we're downgraded.

The old image effect were not volumetric solutions, they were just fake effects, some of which taxed FPS a lot (my VR app went down by 40 FPS by just using the old sun shafts). Also, I think if you want volumetric lightning, then you should head to https://github.com/Unity-Technologies/VolumetricLighting

This is a **post-processing** stack, not volumetric stuff stack.

**Comment by tdbe** [comment]
It was my impression that you had a unified stack so that there would not be any duplication of gbuffer reading, raymarching and extra sampling.

**Comment by pavelkouril** [comment]
I'm not an Unity employee, just a user of the stack; and as a end-user, I would definitely not expect PP stack to have volumetric lightning and fog. Just my two cents, nothing more. :)

**Comment by nestg** [comment]
I support the request.

**Comment by tdbe** [comment]
Somehow I assumed you are from unity. It doesn't really matter, but the way I always thought of volumetric atmospheric / lighting stuff is either it is baked (e.g. uses baked light distance volume 3D textures / voxels) - in which case it should be part of the engine, either it's a gbuffer effect at runtime in which case it's some kind of "filter on the camera" :P

**Comment by Chman** [comment]
Volumetric and post-processing effects are two very different things. Until recently Unity used to put them all (volumetric, lighting, post) in the same basket (not good). We're moving away from that because pure camera effects shouldn't have anything to do with **lighting effects** like SSR, AO, Fog & co. So expect these to be separated (not removed) from the **post-processing** stack in a near future (v2.x currently in dev).

As for volumetrics... It's the same. There's work being done on it but not by us as it's not part of our team goals.
