### ISSUE TITLE
Will bloom update in v2 be back ported to v1?

### ISSUE THREAD

**Issue by wdw89** [Unity-Technologies/PostProcessing#176]
Hello, I notice recently there are some bloom update in v2, liek Mobile optimized and energy conserving. I want to know will these features be back ported to v1? Because v2 is far from stable release now, and I wish we can have new bloom feature in v1. Thanks.

**Comment by Chman** [comment]
Probably not. Bloom in V2 isn't backward compatible because of how much was changed, so porting it to V1 means we'll break compatibility with projects currently using it and that's a big no-no.

Furthermore, Bloom in V2 isn't definitive yet and isn't considered "stable". Porting it to V1 wouldn't make it more stable :)
