### ISSUE TITLE
[V2] Monitor support for OSX/Metal

### ISSUE THREAD

**Issue by ujamer** [Unity-Technologies/PostProcessing#180]
##### What happened?
After importing the package, 2 errors on compute shader appears:
Metal: Compute shader has 384 threads in a threadgroup which is more than the supported max of 256 in this device
Metal: Compute shader has 1024 threads in a threadgroup which is more than the supported max of 256 in this device

These two errors disappears after making the following changes:
In WaveformCompute.compute, change the COLUMNS value from 384 to 256.
In VectorscopeCompute.compute, change the GROUP_SIZE value from 32 to 16.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.0p4, OSX 10.11.6, mac

**Comment by Chman** [comment]
The monitor shaders are quite raw (and by that I mean "dumb & naive") at the moment and because they are editor-only we didn't focused too much on them yet. We didn't have metal/compute at that time so we only tested it on PC GPUs.

For the upcoming big upgrade to this stack we're working on  we want these monitors to be available at runtime too as part of the revamped "debug layer" we have on our roadmap. So eventually we'll have to make a proper implementation of these so that they run on all compute-enabled platforms.

It's not an absolute top priority for now though, but we'll come to it. I'll leave this issue opened in the meantime.

> These two errors disappears after making the following changes:

Doing that will make the compute shaders compile correctly but as a result the monitors data will be invalid. Don't use these monitors if you use this "fix" as they'll be wrong.

As a sidenote... What's your GPU?

**Comment by slime73** [comment]
Metal supports up to 1024 threads per threadgroup in macOS, but only up to 512 on iOS: https://developer.apple.com/metal/limits/

**Comment by ujamer** [comment]
Yeah, the monitor data is definitely wrong after those "fix". It'd be nice to have the debug view, but it's not a big problem. GPU is the integrated one from intel (Intel Iris Graphics 6100).

Huh, it says 1024 thread groups are supported for OSX 10.11 on the table, but it's throwing the max 256 groups supported error on my machine.

**Comment by Chman** [comment]
I forgot about this issue. Monitors in v2 do work on OSX/Metal out of the box now!
