### ISSUE TITLE
Ambient Occlusion doesn't work for meshes without backface culling

### ISSUE THREAD

**Issue by tirbelain** [Unity-Technologies/PostProcessing#187]
##### What happened?
Looking at the debug visualizations from the PostProcessingProfile you can see that the back faces are not rendered for our 2-sided geometry, causing the ambient occlusion of other objects behind the 2-sided one will appear on top of it.

We are trying to render a 2-sided material and have the shader setup to render the mesh twice, first culling the frontfaces and then the backfaces. Disabling culling entirely in the shader doesn't work either (same results).

As a workaround I tried to duplicate the geometry and flip the normals, but that caused the whole mesh to go black. But this seems to be unrelated to the PostProcessing.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity Pro 2017.1.0b4 (also happens in 5.6.0f3)
OS: Windows 10 Pro (x64)
Target platform: standalone windows

**Comment by Chman** [comment]
This is because the 2-sided material you're using doesn't output proper depth & normal info for both sides. SSAO is highly dependent on the quality of the depth & normal buffers (it doesn't know anything about the actual geometry), and if these are missing information it won't be able to do much to fill-in the gap.

2-sided materials can be problematic in a many cases, and this is one of the worst.

Are you running deferred or forward? What shader are you using? Custom? Asset store?

**Comment by tirbelain** [comment]
I would expect the rasterizer to generate correct depth information for rendered pixels if depth write is enabled (it is in our case). Normals are of course a bit different, but I flipped them in the vertex function for the backface rendering.
Passing the normals into the color output caused both sides to be colored differenly, so I expected the normals to be correct. But as I mentioned, the back faces don't show up in the PostProcessingProfile's debug views. My first thought on this was that you might be using replacement shaders that ignore the cull setting (but I not used that feature yet and actually don't know whether it does what I think it does).

We are using forward rendering with a custom surface shader (+ vertex function). Really simple stuff, this is it:
```
Shader "Custom/CheckerBoard"
{
	Properties
	{
		_Glossiness ("Smoothness", Range(0,1)) = 0.5
		_Metallic ("Metallic", Range(0,1)) = 0.0
	}
	SubShader
	{
		Tags { "RenderType"="Opaque" }
		LOD 200

		ZWrite On
		Cull Front

		CGPROGRAM
#pragma surface surf Standard fullforwardshadows
#pragma vertex vert
#pragma target 3.0

		struct Input
		{
			float2 uv_MainTex;
		};

		half _Glossiness;
		half _Metallic;

		void vert(inout appdata_full v)
		{
			v.normal = v.normal;
		}

		void surf(Input IN, inout SurfaceOutputStandard o)
		{
			float2 uv = floor(IN.uv_MainTex * 8);
			float color = (uint)(uv.x + uv.y) % 2;
			o.Albedo = color;
			//o.Albedo = o.Normal * 0.5f + 0.5f;

			o.Metallic = _Metallic;
			o.Smoothness = _Glossiness;
			o.Alpha = 1.0f;
		}
		ENDCG


		ZWrite On
		Cull Back

		CGPROGRAM
#pragma surface surf Standard fullforwardshadows
#pragma vertex vert
#pragma target 3.0

		struct Input
		{
			float2 uv_MainTex;
		};

		half _Glossiness;
		half _Metallic;

		void vert(inout appdata_full v)
		{
			v.normal = -v.normal;
		}

		void surf(Input IN, inout SurfaceOutputStandard o)
		{
			float2 uv = floor(IN.uv_MainTex * 8);
			float color = (uint)(uv.x + uv.y) % 2;
			o.Albedo = color;
			//o.Albedo = o.Normal * 0.5f + 0.5f;

			o.Metallic = _Metallic;
			o.Smoothness = _Glossiness;
			o.Alpha = 1.0f;
		}
		ENDCG
	}
	FallBack "Diffuse"
}
```

**Comment by Kink3d** [comment]
Hi, sorry for the lack of responses.

The problem is that in Forward rendering AO uses the DepthNormal texture for its normals. This is created using a replacement shader and therefore ignores the content of your shader.

To fix this problem you need to alter `Hidden/Internal-DepthNormalsTexture.shader` (you can find this in the Built-in shaders package on our downloads page) to the use the desired culling mode and then tell Unity to use your version. To assign it you need to view Graphics Settings in debug mode. The entry is called `Depth Normals`.

Either way not an issue in AO. Thanks for reporting all the same :)
