### ISSUE TITLE
Animating effects wasn't trivial in v1 and still isn't in v2.

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/PostProcessing#208]
##### What happened?
Mostly a suggestion, but wouldn't it be nice to have built-in support for animating effects on a PostProcess volume? Effects parameters are exposed in the editor, but nowhere to be found in the Animation panel. 

I know we can create a script ourselves that duplicate a profile at runtime and then act as a middleman between the animator and the volume, but I believe this part should be shipped alongside the stack, as animating stuff in Unity is pretty common.

Prototyping and developing aswesome stuff would be much faster with that layer built-in.

**Comment by Chman** [comment]
> I know we can create a script ourselves that duplicate a profile at runtime

You don't have to duplicate the profile. See [this](https://github.com/Unity-Technologies/PostProcessing/wiki/%28v2%29-Scripting-the-stack#profile-editing). It works the same way it does with materials.

> Mostly a suggestion, but wouldn't it be nice to have built-in support for animating effects on a PostProcess volume? Effects parameters are exposed in the editor, but nowhere to be found in the Animation panel.

The problem is that the animation panel as it is currently is very limited (basically, it can only animate a few types of properties serialized straight into a MonoBehaviour). For the stack to be completely extensible (custom effects) and blend-able through the use of volumes, we had to abstract things away and use more advanced data structures. These, unfortunately, can't work with the Animation tool. Everything would have to be hardcoded if we wanted to support it. Some info about the current architectural choices are available [in this file](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Runtime/PostProcessVolume.cs) (the big comment at the top).

Now, this framework really puts the emphasis on volume blending, and I would argue that this feature in itself makes it a lot easier to animate than V1. Scripting is also much easier. We're also working on a deeper integration with Timeline (which is where you'll probably want to look if you want complete control over the animation of each parameter - right now you can only animate the weight factor but more will come) and Cinemachine, plus _other things_.

Shipping an "all in one" hardcoded component to bridge with the Animation tool is currently not planned, as it makes little sense with the dynamic nature of the override system as a whole (and will lack features as soon as you add custom effects grabbed from the internet or the asset store). You can still iterate very quickly using the override system and the weight factor (which can be animated through the Animation tool btw, and it allows you to actually animate several values/overrides at once without having to animate each of them by hand).

Note: I'm not saying your request is invalid, far from it, I'd love complete support for the Animation tool. V2 is currently being used in several projects and I see artists work very quickly with it once they understand the power of the override system. Give it a try :) Granted, we lack good documentation at this point, but it will come. Also, it's still a WIP, we have a few more "quality of life" improvements to make.

**Comment by AlexandreFiset** [comment]
Cool thank you for the detailed answer :)

**Comment by Chman** [comment]
FWIW, we're evaluating adding a small template/quick setup system so that you don't have to go over the initial setup. Ultimately you should only have to select a platform & quality and click a button to have a good default preset to start tweaking from.
