### ISSUE TITLE
Bug 923939

### ISSUE THREAD

**Issue by jbonastre** [Unity-Technologies/PostProcessing#209]
##### What happened?
https://fogbugz.unity3d.com/default.asp?923939_vqodg46dvpsqqrt5

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.2f1, Windows 10 x64, windows

**Comment by Chman** [comment]
I opened your project, you're missing all the post-processing shaders, editor resources and textures. Make sure you import the full content of the PostProcessing package.

**Comment by jbonastre** [comment]
Hi @Chman , reimporting the full post-processing code, I get the same issue. I´ll add this info to the bug report

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.PostProcessing.TrackballGroupDrawer.TryGetDisplayValue (Color color, UnityEditor.SerializedProperty property, UnityEngine.Vector3& output) (at Assets/simuzen/CommonTools/PostProcessing/Editor/PropertyDrawers/TrackballGroupDrawer.cs:166)
UnityEditor.PostProcessing.TrackballGroupDrawer.OnWheelGUI (Rect position, Int32 size, UnityEditor.SerializedProperty property) (at Assets/simuzen/CommonTools/PostProcessing/Editor/PropertyDrawers/TrackballGroupDrawer.cs:125)
UnityEditor.PostProcessing.TrackballGroupDrawer.OnGUI (Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at Assets/simuzen/CommonTools/PostProcessing/Editor/PropertyDrawers/TrackballGroupDrawer.cs:47)
UnityEditor.PropertyDrawer.OnGUISafe (Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at C:/buildslave/unity/build/Editor/Mono/ScriptAttributeGUI/PropertyDrawer.cs:22)
UnityEditor.PropertyHandler.OnGUI (Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, Boolean includeChildren) (at C:/buildslave/unity/build/Editor/Mono/ScriptAttributeGUI/PropertyHandler.cs:142)
UnityEditor.EditorGUI.PropertyFieldInternal (Rect position, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, Boolean includeChildren) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:5213)
UnityEditor.EditorGUI.PropertyField (Rect position, UnityEditor.SerializedProperty property, Boolean includeChildren) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorGUIBindings.gen.cs:1034)
UnityEditor.EditorGUI.PropertyField (Rect position, UnityEditor.SerializedProperty property) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorGUIBindings.gen.cs:1029)
UnityEditor.Editor.OptimizedInspectorGUIImplementation (Rect contentRect) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorBindings.gen.cs:273)
UnityEditor.GenericInspector.OnOptimizedInspectorGUI (Rect contentRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/GenericInspector.cs:32)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1209)
UnityEditor.InspectorWindow.DrawEditors (UnityEditor.Editor[] editors) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1019)
UnityEditor.InspectorWindow.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:358)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

**Comment by Chman** [comment]
It's not the same issue. The previous issue was about Unity not finding the shader to render the trackballs. This one is due to something else. After taking a closer look at your project, it seems that you're using a custom asset type to store post-processing profile data in it (as well as other stuff). So, basically, you made your own profile.

The Trackball PropertyDrawer is meant to be applied to the struct holding the three trackballs. It wasn't designed to be used on raw serialized data (fwiw that changed in V2 but this is a bit offtopic). Adding to that, the drawer uses reflection to grab pre-computed data from the component, which won't work with a custom profile.

Your best course of action at this point is to simply disable the property drawer. Comment [this line](https://github.com/Unity-Technologies/PostProcessing/blob/v1/PostProcessing/Editor/PropertyDrawers/TrackballGroupDrawer.cs#L8) and it will display a raw color field for each line.

**Comment by jbonastre** [comment]
Cool, it works.
