### ISSUE TITLE
Shader compile errors under Linux/Vulkan, Unity 5.6.0p1 #157

### ISSUE THREAD

**Issue by longmang** [Unity-Technologies/PostProcessing#211]
As specified in the thread this is fixed for standalone builds. It still occurs on Cloud Build with the Android target. 

....
[Unity] Shader error in 'Hidden/Post FX/Screen Space Reflection': '' : compilation terminated at line 141 (on vulkan)
[Unity] Shader error in 'Hidden/Post FX/Screen Space Reflection': 'z' : vector field selection out of range at line 141 (on vulkan)
...
[Unity] Player export failed. Reason: 2 errors
! build of 'steam-museum-android' failed. compile failed
publishing finished successfully.

**Comment by Kink3d** [comment]
Hey,

Can you tell us what your Unity version for this target is? There's an issue with Cloud Build where if you select "Latest 5.x" you actually are building from 5.6.1f1 (where this issue still reproduces), but if you build with "Latest 5.6" It builds with the latest patch release (where the issue is fixed). Cloud Build team are reportedly working on this.

Thanks

**Comment by longmang** [comment]
Hello

Thank you for the reply. I raised a ticket with the Cloud Build support and they conveyed the same information, so I changed the Build Target and as you said it was fixed.

Regards
Paul
