### ISSUE TITLE
[Suggestion] Depth blend of effects (depth weight?)

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/PostProcessing#213]
The scenario: In most modern 3D games, distinct color grading parameters are used for objects close to the camera than to the ones in background. For instance, in Firewatch, the horizon can look bluish and washed out while everything close to the camera is contrasted and often warm in colour. 

The problem: It is currently not possible to bind an effect power to the depth of the image. 

My suggestion (which might not be the best): Having a depth power, or depth weight, curve as a parameter in the Volume component. Developers could then use the value to augment or reduce the power based on the depth of the image. One could for instance create one volume for close-to-the-camera color grading, with a curve set to full power at 0 and 0 power at 1, plus another volume for the horizon and an inverse curve. Considering a camera with clipping planes of 0 and 100, at 50 the result would be an equal blend of the close and far effects.

It may not be suitable for all effects of the world, but still pretty useful for many of them. At least it should be there for Color Grading.

**Comment by Chman** [comment]
That's something we wanted to add for a long time because as you said, it's quite powerful (and the concept of depth-based color grading is just great).

There's quite an important downside to it though, and it's the main reason why we haven't implemented it yet: it would only work on opaque objects. Transparent materials (water, glass...), particles, or any other alpha blended effect won't be affected by the grading at all. At least not via post-processing, it would need to be injected into the object shader itself (performances will suffer and all shaders will need patching). That's quite problematic IMO.

So even though I **love** the idea, it's kinda hard to apply in practice. Of course for grading (and that alone, not the full volume because that's another story) it would work in some cases but when we add a feature we need to make sure it works in most if not all cases, as the stack is meant to be quite generic.

With that said, with V2 is should be fairly easy to push a [custom effect](https://github.com/Unity-Technologies/PostProcessing/wiki/%28v2%29-Writing-custom-effects) at the `BeforeTransparent` injection point and do custom grading in the distance. Eventually, if we have time and once everything is perfectly stable, we'd like to create a secondary repository for post-processing extensions that would hold random, "unofficial" effects for users to play with. It could become a "community" repository of some sort.

**Comment by AlexandreFiset** [comment]
Thank you Thomas for the blazing-fast answer! Indeed the transparency of objects is quite troublesome, yet avoidable by clever environment design ;p But yeah, you're right that it really is hard to apply and not for everyone. 

The community repo is a great idea, as we're playing around a lot with the v2 and there are few things we would love to share in the long run.

Cheers!
