### ISSUE TITLE
Camera rendering to texture leads to null exceptions

### ISSUE THREAD

**Issue by andrew-raphael-lukasik** [Unity-Technologies/PostProcessing#222]
##### What happened?
Camera with Viewport Rect {0,0,0,0} (silly mistake I know) and rendering to texture leads to null exceptions:
> NullReferenceException: Object reference not set to an instance of an object
UnityEngine.PostProcessing.EyeAdaptationComponent.get_active () (at Assets/PostProcessing/Runtime/Components/EyeAdaptationComponent.cs:37)
UnityEngine.PostProcessing.PostProcessingBehaviour.OnGUI () (at Assets/PostProcessing/Runtime/PostProcessingBehaviour.cs:307)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.2f1, Windows 10, standalone

**Comment by Kink3d** [comment]
Hi,

This is a serialisation bug caused by `OnPreRender` being called before `OnEnable`. It's incredibly tricky to pinpoint a fix on it. Luckily it shouldn't cause any real issues (and only reproduces infrequently). It should be noted that V2 of the stack does not hit this bug as we don't really use standard Monobehaviour events anymore.

Thanks
