### ISSUE TITLE
EyeAdaptationComponent - NullReferenceException

### ISSUE THREAD

**Issue by KaiSoellch** [Unity-Technologies/PostProcessing#23]
i get this all the time

`NullReferenceException: Object reference not set to an instance of an object
UnityEngine.PostProcessing.EyeAdaptationComponent.get_active () (at Assets/PostProcessing/Runtime/Components/EyeAdaptationComponent.cs:37)
UnityEngine.PostProcessing.PostProcessingBehaviour.OnGUI () (at Assets/PostProcessing/Runtime/PostProcessingBehaviour.cs:282)`

by the way great job - this plugin roxx 👍

**Comment by KaiSoellch** [comment]
i am using Unity 5.4.2f2

**Comment by Kink3d** [comment]
Hi,

Unfortunately I have been unable to reproduce this. Could you provide a small project in which you can reproduce this issue? Also what OS (and OS version) are you running?

Thanks

**Comment by KaiSoellch** [comment]
Hi,

my project is very big (2,7 GB).
i'm on windows 10 - 1511 (Build 10586.679)

i think my particle system is causing this problem

**Comment by Kink3d** [comment]
Hey,

Im sorry but I have no way of reproducing this without some sort of example. Are you unable to get this error in a smaller project?

**Comment by KaiSoellch** [comment]
Unfortunately I can not recreate the problem outside of my project 😢 i tried everything...

**Comment by MaxEden** [comment]
**Reproduction steps:**
1. Prefab with a camera component and PostProcessingBehevior component
https://i.imgur.com/WyIUdvE.png
2. Disable camera component
https://i.imgur.com/R9FCi6D.png
3. Click apply
https://i.imgur.com/N1Tn2GB.png
4. Behold the issue
https://i.imgur.com/VletU0Q.png

**Comment by zachkinstner** [comment]
I know this is an old/closed ticket, but I was also getting this error message. I found a workaround, so I'm posting it here in case it helps anyone.

See also #222 which suggests the error is related to rendering a camera to a texture. That description matches up with my scenario (specifically, toggling to a "mixed-reality mode" in a VR app).

All during the same frame,  these post-proc components are: 

- 1) Recreated/rebuilt, then 
- 2) Queried if "active" from `OnGUI()`, which leads to the error message due to a null `model` property, then 
- 3) Initialized with a non-null `model` property, via `PostProcessingBehaviour.OnEnable()`

I added my workaround in `PostProcessingBehaviour.OnGUI()`, placed on a line after the `if ( profile == null ...` conditional:

```
if ( m_EyeAdaptation.model == null ) { return; }
```

The net result is that, for a single frame while these post-proc components aren't fully initialized, they do not get their own `OnGUI()` methods called by `PostProcessingBehaviour.OnGUI()`. This is the same thing that would occur if the components were non-active -- it seems harmless, and avoids the error messages.
