### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by rico345100** [Unity-Technologies/PostProcessing#231]
##### What happened?
I just cloned repo and paste to my assets folder, but it prints:

```text
Assets/PostProcessing/Runtime/Effects/AutoExposure.cs(15,6): error CS1502: The best overloaded method match for `UnityEngine.Rendering.PostProcessing.PostProcessAttribute.PostProcessAttribute(Type, string, bool)' has some invalid arguments

Assets/PostProcessing/Runtime/Effects/AutoExposure.cs(15,18): error CS1503: Argument `#1' cannot convert `System.Type' expression to type `Type'

Assets/PostProcessing/Runtime/Effects/Bloom.cs(10,6): error CS1502: The best overloaded method match for `UnityEngine.Rendering.PostProcessing.PostProcessAttribute.PostProcessAttribute(Type, string, bool)' has some invalid arguments

Assets/PostProcessing/Runtime/Effects/Bloom.cs(10,18): error CS1503: Argument `#1' cannot convert `System.Type' expression to type `Type'

...
```

There are 57 errors. Using v1 gives me same result :(
If I move PostProcessing to "assets/plugins", it seems work(no errors) but most of effects not working with errors.

What is happening? How do I solve this problem?

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
5.6.1f1, Windows 10. Target platform is also Windows.

**Comment by Chman** [comment]
`Type` is a core class of the .Net/Mono runtime. So either your installation is broken or another script in your project is shadowing the internal `Type` class (which would be very bad in any case). Please run a search in your project folder, this could be caused by an asset downloaded from the Asset Store. More often than not these aren't namespace'd correctly and class name collision occurs.

**Comment by rico345100** [comment]
Thanks, I knew that you were commented but I was too busy so I couldn't checked and forgot. It works now, thanks!
