### ISSUE TITLE
Dof looking a GameObject

### ISSUE THREAD

**Issue by ghiboz** [Unity-Technologies/PostProcessing#25]
Hi all!
I've installed the suite instead the scripts in standard assets/cinematic effects and looks great!!
I've a question: in the Dof script I've had a possibility to set a gameobject to make a focused point, with this dof I doesn't have this possibility...
how can I do? thanks!!

**Comment by alastaira** [comment]
Yes - I second this is a really useful feature of the existing DoF asset that I'd like to see implemented in the PostProcessing DoF effect - otherwise we have to write a separate script to manually recalculate the focus distance from the camera to the desired transform.

**Comment by Chman** [comment]
We can't currently have an object field in the DoF setting panel because the whole thing is an asset (and we can't make a reference to a scene object in an asset as it doesn't live in the scene). There are a few examples and complete scripts to do that (see #11 or [PostProcessingUtility](https://github.com/keijiro/PostProcessingUtilities)).

We're working on a more flexible solution (no ETA).

**Comment by ghiboz** [comment]
thanks @Chman !! the [PostProcessingUtility](https://github.com/keijiro/PostProcessingUtilities) sounds good!!
