### ISSUE TITLE
Alpha is discarded after applying the post processing behaviour

### ISSUE THREAD

**Issue by WayneDeBock** [Unity-Technologies/PostProcessing#252]
##### What happened?
The alpha channel gets discarded after applying the post processing behaviour.
##### Post-processing stack version (v1, v2)?
v1
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.2f1, Windows, Editor/Standalone Windows

**Comment by Chman** [comment]
v1 doesn't have any sort of alpha propagation because a lot of the effects rely on the alpha channel to store additional informations (bloom, fxaa, depth of field, etc) for performance reasons. We added experimental alpha propagation to v2 but it's way too big of a change to port to v1 as it would require a rewrite of most of the effects at this point.

So v1 will stay that way unfortunately. We'll make sure it doesn't happen in v2 as it's needed for proper AR support and rendering on transparent render targets.

**Comment by WayneDeBock** [comment]
Hi, thank you for the quick response.
We will have a look at v2 then.

**Comment by mikson60** [comment]
Hey,

Is this not an issue in the current v2 version?

Thank you!

**Comment by Chman** [comment]
Unless something broke recently it shouldn't be an issue in v2 anymore, although a few effects don't work really well with alpha yet with regards to visual quality (Depth of Field comes to mind).

**Comment by mikson60** [comment]
Thank you!

I just downloaded the v2 and the issue is fixed indeed.
