### ISSUE TITLE
(V2) Effect sorting

### ISSUE THREAD

**Issue by erherhh4herh** [Unity-Technologies/PostProcessing#272]
This was a feature missing in V1 as well. In V2 it is more crucial than before as now the effect order is based on the order in which the effects are added, which can't be changed unless you remove the effects and add them back in the preferred order. My suggestion: Add a context menu item in the overrides area on each effect tab to move an effect up or down (much like components). Being able to drag-and-drop effect tabs would be even better! Effectively giving users full customization over the order of image effects (excluding command buffer-based effects).

Please and thank you,
erherhh4herh.

**Comment by Kink3d** [comment]
Hi,

Removing and re-adding the effects does not change the order in which the effects are applied, it only changes the UI. The default effects that ship with the stack are applied in a predetermined order that is the correct order in which to apply those effects.

Thanks

**Comment by Chman** [comment]
Also note that if you're talking about "custom user effects" you can in fact [reorder them at will](https://github.com/Unity-Technologies/PostProcessing/wiki/%28v2%29-Writing-custom-effects#effect-ordering). Like @Kink3d said, the order that is displayed in the profile isn't representative of the actual rendering order. The reason for that has to do with the fact that it's all part of a big override stack and there's no good way to show proper ordering when you have several volumes with different overrides interacting & blending with each others in your scenes. You shouldn't think about post-processing as a set of separate component on your camera - this was the old, inefficient way of doing things in Unity -  but as a chunk of the rendering pipeline.

When it comes to standard effects (the ones that come by default with the stack) they have to be done in a specific order for performance reasons and quality. And because it has to make sense. I've seen too many people apply bloom or do exposure adjustments after tonemapping...
