### ISSUE TITLE
Isolating Effects to Objects (Make Cube A glow and B not)

### ISSUE THREAD

**Issue by harperAtustwo** [Unity-Technologies/PostProcessing#278]
##### What happened?
I used to be able to isolate effects. Using 2 cameras and layers, I would have an FX camera that would only see items that need to be rendered with a bloom effects on it.  Now, no matter what I do with the layers/Cameras. The bloom FX is on everything, instead of it just being on one of the objects. 

![screen shot 2017-09-06 at 11 34 10](https://user-images.githubusercontent.com/23457841/30120689-93ec534a-92f7-11e7-93a4-b4408b7aab80.png)

##### Post-processing stack version (v1, v2)?
Both. 

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.2.0b7 64bit, Mac OS, IOS

**Comment by Kink3d** [comment]
<img width="263" alt="screen shot 2017-09-18 at 10 51 12" src="https://user-images.githubusercontent.com/11135817/30556349-607325e0-9c5f-11e7-97ec-dfb580c041bf.png">

This behaviour still works. In the image above I have one camera (with post-processing) that renders first and then another camera that renders afterwards with Dont Clear clear flags. Obviously this doesnt work in practice as objects on the second camera with render over the bloom effect etc.

Otherwise you can do proper compositing to achieve this.

**Comment by harperAtustwo** [comment]
If that is the case, how would you keep the background like skybox from blurring? I realize this is an old question just ran into it again.
