### ISSUE TITLE
OpenGl Frieze in first run

### ISSUE THREAD

**Issue by Gray-Master** [Unity-Technologies/PostProcessing#28]
If OS = Windows & driver = OpenGLCore/OpenGL ES Every day in first run in editor or building application if replace post process stack on camera (step between others posteffects zones, such us surfacing out of the water) exist mini frieze оn 1-1.5 seconds. in next runs frieze is not exist.
PS. in DirectX is all Ok.

**Comment by Chman** [comment]
Considering that it only happens on the first run, it may has something to do with the initial compilation of the uber shader (which is cached and reused afterward)... It's a big shader with lots and lots of variants. According to you DirectX is fine though, so that would be an issue with the GL backend... It's hard to say, really, what's going on.

Out of curiosity, what GPU are you running Unity on ?

**Comment by Gray-Master** [comment]
i use nVidia GTX 750 ti.
and one moment too - after long time comfig parameters & run this problem
exist too.  i do not known another method seen this truble .

2017-01-04 20:02 GMT+06:00 Thomas <notifications@github.com>:
