### ISSUE TITLE
Depth of field debug/vizualize view?

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/PostProcessing#284]
##### What happened?
The new Depth of field effect lacks a proper "visualize" mode to finetune its properties. It makes balancing the effet longer than other solutions. It would be nice to have it somewhere; either in the PostProcess debug component of as a boolean value on the effect itself.

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Standalone Windows

**Comment by Chman** [comment]
Add the `PostProcessDebug` component to your camera (or anywhere in your scene, as long as you point it to a `PostProcessLayer`). Debug views & monitors have been moved out of the main UI for performance reasons (no more OnGUI calls if you don't need them at runtime), to keep the mainline stuff clean and to allow users to make their own debug menu (consider the code of `PostProcessDebug` as an exemple as to how to make a debug component).

**Comment by AlexandreFiset** [comment]
The problem is that this setting has been **removed**, not **moved**. It is **not** in the effect settings, **nor** in the debug view.

**Comment by Chman** [comment]
It hasn't been removed. Like I said, it's in the debug component.

![image](https://user-images.githubusercontent.com/849090/30280274-a0d05eaa-970f-11e7-81be-e28cf4c840b5.png)

**Comment by AlexandreFiset** [comment]
The latest release is more like this:
![image](https://user-images.githubusercontent.com/850692/30289469-39e225e4-96fa-11e7-9f2b-eefc65e8a0f5.png)
So I assume this has been resolved since the latest release (11 days ago)?

**Comment by AlexandreFiset** [comment]
Nevermind, I just checked the latest commits and it looks like you added the overlays on Sept. 7... so they haven't been released yet. 

It is a bit confusing that the PostProcessing and ScriptableRenderLoop projects don't work the same way. On the SRP, users have to use the releases for the package to be guaranteed to work. On the other hand, filing a bug here for the latest release get instant-closed, with an explanation that do not work in a release.

Anyway, I'll try to sync with the latest unreleased version and see how it goes.

**Comment by Chman** [comment]
SRP is experimental and hasn't been released officially, neither does Post-processing v2. The prebuilt beta packages are just here for convenience. We close issues that are fixed in the repository, like it's usually done in most software development processes (even Unity itself, if you report a bug it'll go into Fogbugz and will be closed once it's fixed in trunk, before the actual release). It'd be a mess if we didn't do this, especially for something that hasn't been released where you expect fast iterations and official support isn't available yet.

As for the difference in processes between SRP and Post-processing, it comes from the fact that SRP is a long-term / long-dev global feature whereas Post-processing is a specific, self-contained project. You can't really compare them, especially since SRP heavily depends on the work done in Unity on the C++ side. Post-processing works on current release versions (starting with 5.6 for v2).

We work on public repositories so that people can see what's going on and because we'd rather give you a taste of what's to come rather than keeping you in the dark, but until they reached an official release milestone you're not supposed to use in-dev features in production.

Lastly, here's a quick excerpt the SRP readme :)

> NOTE: this is a testbed for a Unity feature that has not shipped yet! The latest commits in this project does not work with any public Unity version, and things in it might and will be broken.
[...]
Did we mention it's a very WIP, no promises, may or might not ship feature, anything and everything in it can change? It totally is.
