### ISSUE TITLE
(v2) Why BuildCommandBuffers called twice?

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#302]
I see BuildCommandBuffers both called in OnPreCull and OnPreRender, even if the call in OnPreRender has a right stereo eye condition, but it still would be called in OnPreCull for a right eye.

I'm not very sure for this, so I report this issue. If I'm right, I think should remove the call in OnPreCull, and modify OnPreRender:
```
        void OnPreRender()
        {
            // Unused in scriptable render pipelines
            // Only needed for multi-pass stereo right eye or stereo is not enabled  
            if (RuntimeUtilities.scriptableRenderPipelineActive ||
                (m_Camera.stereoActiveEye == Camera.MonoOrStereoscopicEye.Left))
                return;

            BuildCommandBuffers();
        }
```

**Comment by robbiesri** [comment]
I'm not sure what the issue is here?  Are you reporting an issue from inspection, or have you run into an actual repro of a bug?

The reason it's called twice here for the right eye is that OnPreCull does some general setup, and builds command buffers for the left eye.  The bulk of OnPreRender code only happens on the right eye, and when it does run, it does need to re-build the command buffers for the right eye specifically (for now).
