### ISSUE TITLE
(v2) Option to disable dithering

### ISSUE THREAD

**Issue by j4james** [Unity-Technologies/PostProcessing#320]
##### What happened?

I was trying to cut down on my app size by getting rid of what I though were unused blue noise textures, only to find that they are required by the dithering effect, which seems to be an unremovable component in the v2 stack.

Not a major problem, but it would be nice to have an option to disable the dithering when it's not wanted, like there was in the v1 stack.

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.1.0p4, Windows 10, standalone Windows/Mac

**Comment by Chman** [comment]
We don't have any plan to make dithering optional at this point, it's hardcoded into the framework to save on shader combinations (and it's pretty cheap anyway) and thus save some space (each shader combination takes up space as well, especially considering that our Uber shader can get pretty big). All in all you wouldn't save any space (and potentially lose more) by adding a dithering toggle.

FWIW, the bluenoise textures required for dithering take 256KB total, which isn't _that much_. You can remove the 256px ones if you don't need SSR though to save some space (512KB total).

**Comment by j4james** [comment]
Thanks for the response. That seems perfectly reasonable. I didn't realise the dithering was only using the one bluenoise set.

**Comment by sschoener** [comment]
I know that this is an old issue, but please bear with me. I am currently running on Unity 2018.1 with the 2.0.5 preview version of the v2 post processing stack. I am using the post-processing for rather dark and calm scenes (read: star fields) and spent hours the other day trying to figure out where this grizzling noise comes from that is oh so very annoying during gameplay (even with all other effects disabled!). Turns out that this is the dithering -- it is very well visible at runtime in scenes that do not involve a lot of action (most pixels will actually have a constant color or change very slowly).

I have created [two small GIFs](https://imgur.com/a/YhoCamA) that show a small portion of my screen (without any zoom or anything, it is just the same small portion of my entire screen). It should not be hard to see which of the two images contains dither and which doesn't. This, of course, should be taken with a grain of salt (after all, it's a compressed GIF!), but I can assure you that the effect is very well visible in-game at runtime.

As an added bonus, I should point out that dithering also interacts quite badly with GIFs. For example, the dither-GIF I have created is about 3 seconds of 'gameplay' at a size of roughly 1.3mb. The no-dither-GIF needs only 300kb for the same time span. It seems like [there are others with other GIF problems](https://twitter.com/thomasastle/status/949358321575739392), which I suspect are due to dithering (since Tom Astle from that tweet says that the problem is not as bad when using LiceCam for the GIF recording, I have used LiceCam for the GIFs linked above).

This automatic addition of dithering makes it very difficult to embrace the new post-processing stack which I otherwise find to be very useful. I hope you can reconsider your position on this topic.

**Comment by thecosmicboy** [comment]
Having the exact same problem as @sschoener 

It's impossible to use the new V2 Stack in darker situations without it garbling everything, this dither occurs with just having the Post Process Layer enabled without any effects. Surely this isn't right?

Comparison between the two here [https://image.ibb.co/gGYFRJ/Dither.gif](url)

**Comment by Chman** [comment]
I am definitely taking these last two posts in consideration and I intend to look into it soon - things are a bit slow these days as I'm traveling.

So I may end up turning this into an option. It's also very possible that something broke or is no working correctly as it shouldn't be that visible.

**Comment by thecosmicboy** [comment]
Thank you for this!

Unfortunately i'm having trouble locating the Dithering.hlsl file, it's not included in the V2 Post Process Stack install or the current V1 asset in the asset store. Was it included in a older release?

Cheers

**Comment by Chman** [comment]
It's only in v2, you'll find it in [/PostProcessing/Shaders/Builtins/](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Shaders/Builtins/Dithering.hlsl).

**Comment by thecosmicboy** [comment]
Ok so problem I was having was I didn't realise if I install a package through the package manager it is not located in the project, I thought that's how I was supposed to install it in 2018.1. Had to completely remove it in the package manager and import the GitHub version to access the file inside the project.

I then tried replacing the code and it worked a treat, no more dither thank you! :) [Image](https://image.ibb.co/b4yLBJ/Capture.png)

**Comment by thecosmicboy** [comment]
Thank you Thomas! Scene looks 100x cleaner :)

**Comment by Chman** [comment]
A better fix has been pushed to 4bfd2ef (and will be part of the next release).

**Comment by Chman** [comment]
Have you tried the fix that got pushed yesterday? Because "clean black" will stay "clean black" with it and dithering will only be applied where necessary. This was a bug in gamma mode, it's now fixed.

Adding a toggle for dithering means adding yet-another shader keyword that will double the number of shader variants (and thus slowing down shader compilation a lot).

**Comment by Alexandros1313** [comment]
hi @Chman , I actually didn't tried the fix. I will.
Thank you.

**Comment by DaveLomas99** [comment]
I realise commenting in an old and closed thread may be futile, but anyway...

I need to output image files containing per-pixel distance from camera. I have a post-process shader which calculates the right values and encodes the resulting float into an RGBA32 render texture, which I can then read back into a Texture2D on the CPU and save as a .tga file.

That's all working great, apart from the unwanted dithering pass is significantly distorting the outputted values, making it unusable for our purpose.

I would dearly love some way of disabling the dithering - I don't care if the shader still runs as long as the amount of noise added is somehow dialled right down to zero. I work collaboratively as part of a team, and so hacking the .hlsl file in the PackageCache folder is not really a robust and sustainable option.

**Comment by CarlLee** [comment]
Dithering kills performance on mobile. Even if I only use my custom effects made only for mobile.

**Comment by TheLastBanana** [comment]
I'm using the latest version of the package with the gamma fix and still finding that dithering is being applied to solid colors where I'd rather it wasn't. Black stays black, but other colors look spotty.

I realize that adding more shader variants may be out of the question, but is there any way to expose this? Having to hack Dither.hlsl in package code just to get around this is not a great workflow.

**Comment by DaveLomas99** [comment]
@TheLastBanana  - totally agree about hacking files in the installed package, have a look at my forum post from a while back and see if that helps you:

https://forum.unity.com/threads/new-post-processing-stack-pre-release.435581/page-20#post-4538242
