### ISSUE TITLE
[V1][V2][PS4] Stack overhead is large (compared to components)

### ISSUE THREAD

**Issue by Maylovy** [Unity-Technologies/PostProcessing#329]
##### What happened?
PS4 performance of the post process stack is poor when using only few of the effects, we loose about 10 to 15 fps using the stack in comparison to using individual effects on their own on camera. There is some overdraw that takes about 3ms ("BuiltinStack" among others) shows as "other" in the profiler.

We use AA, Bloom, MiniEngine AO, Vignette and Color Grading (the old one from cinematic effects).
If we use same effect with stack V2 we loose performance significantly (as mentioned about 10-15 fps, target is 60), with V1 a bit less but still.

My question is, is it possible to extract the code for Color Grading from the stack (V1 or V2) as the new ones are far more advanced compered to the old one?

Would appreciate any help in this matter. 

##### Post-processing stack version (v1, v2)?
V1, V2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.1.1p2, Windows, PS4

**Comment by Kink3d** [comment]
Hi,

We are very unlikely to provide individual versions of our effects. This is for a few reasons, mainly maintenance cost. What we would be more interested in is why you are seeing this overhead to begin with. We will investigate.

Thanks

**Comment by Maylovy** [comment]
Hey,

If You need any examples let me know. We have not tested it on an empty scene but in our game its like that:
Standard scene has a lot of single material shadow proxies (only proxies cast shadows) and a lot of surface shaders (standard) usage for enviro + every case had HX volumetrics ON before any of post process. Deffered of course. Realtime GI.
Devmode on PS4 - profiler shows:
No post process- 14 ms
![performance_no_effects](https://user-images.githubusercontent.com/32575086/31667444-c4abc01a-b34f-11e7-8ccd-4acc47f82df2.png)

Old post process from cinematic: AA, Bloom, Color grading tone mapping 15 ms
![performance_old_postprocess](https://user-images.githubusercontent.com/32575086/31667462-cfaaba70-b34f-11e7-8039-77d15b321874.png)


Same effects but stack V2 versions 16,5 ms
![performance_stack_full](https://user-images.githubusercontent.com/32575086/31667473-d7e7447e-b34f-11e7-8cec-513cdea49f34.png)


Stack ON but no effects 14,8 ms
![performance_stack_empty](https://user-images.githubusercontent.com/32575086/31667478-dd9f0d84-b34f-11e7-9941-b17bfb9bb86e.png)


Stack itself without any effects takes 0,8 ms on PS4. As You can see these 0.8 ms is to have or not to have 60 fps. We still need some GPU for vignette and AO but those are things we can let go on consoles.


Oh,, and it is rendered in 990p.

**Comment by Chman** [comment]
There are a few things to note here.

Let's begin by looking at the "empty stack" cost. At 1080p on a PS4 non-Pro, an empty v2 stack uses 0.5ms here (I highly recommend you switch to Sony's RazorGPU for PS4 profiling) and it's important to understand that "empty" doesn't mean it does nothing. In this case, with no effect it'll still do a NaN killing pass (can be disabled in the layer options) and 8-bit dithering. These two are basically free, you're essentially paying the cost of the final blit. But it'll be amortized when adding other effects.

Now, when it comes to comparing single component vs multi-components it would be best to compare with the same effects - which you can't really do in this case. V2 is not simply "old/V1 with volumes", it's almost a complete rewrite of each of the effects and most are of much higher quality. Following your example, Bloom v2 is _much more_ higher quality than the older bloom and consequently costs more. With that said, Bloom has a `Mobile Optimized` toggle that makes it _a lot_ faster at the expense of quality (visually similar to the old one). A lot of v2 effects have fast paths that you would definitely use on consoles and lower end hardware (I do agree that the name `Mobile Optimized` isn't the best though).

Next you'll want to look at the big picture. Most games nowadays use a plethora of post-processing effects. If you only need a single or two effects then sure, doing an individual blit for each might be faster than deploying a big framework that has an initial cost. But if you need more, then this initial overhead is quickly eaten away and the stack will end up being faster than using individual components. For instance, Vignette & Color Grading are virtually free as soon as another effect from the combined stack is enabled (e.g. Bloom).

We've ran a lot of performance tests (and we've had game studios report the same), in real-world scenarios with many of the effects enabled v2 is much faster than using individual components and look a lot better visually. In the end it's all about what you need. If you prefer the look of the older effects and you're happier with them... You should use them :)

> My question is, is it possible to extract the code for Color Grading from the stack (V1 or V2) as the new ones are far more advanced compered to the old one?

No plan on that. You'll have to do it yourself if you really want it. If you do it I recommend you use the Color Grading code from v2, it's been much improved since v1 and should be easier to port too.
