### ISSUE TITLE
Post processing stack overwrites the users DepthTextureMode

### ISSUE THREAD

**Issue by TJHeuvel** [Unity-Technologies/PostProcessing#33]
In our project we're mixing the postprocessing stack with some other effects, like global fog. For this to work we need to set the DepthTextureMode to Depth, however when all effects are disabled its always being set to none. 

Ideally the stack would remember the users options somehow, though i dont see how that can be done easily. For us a good solution was to have a default mode added to the profile. 

See pull request: https://github.com/Unity-Technologies/PostProcessing/pull/32

**Comment by Chman** [comment]
I agree this is a problem. The first version of the stack would save the current depth texture mode and reapply it at the end, but it turns out it's not a good solution either because the user could still dynamically add new effects before the stack and thus the saved state would be out of date (and checking this every-frame would be overkill). Another issue was motion vectors as they have a one-frame delay to be enabled/disabled with the current render loop and it didn't play well with a state-saving scheme. So this state saving solution was hit and miss.

Your solution works if you know how the other effects in your stack work and what depth texture modes they require. You also have to keep in sync with whatever effect you add during production. Unfortunately we don't expect users to know about all of this (and they shouldn't have to know, it should work out of the box). So I'm not really in favor of adding an obscure field to the UI that only developers would understand and would confuse artists (who are the target of this stack to begin with).

The other solution is to not do anything and not disable any state set by the stack, but that would result in state leaking and we certainly don't want that, especially when working with the Forward rendering path.

I'll leave this issue opened until we work out a better solution.

**Comment by TJHeuvel** [comment]
Thank you very much for your reply, I understand that our solution isn't ideal for general use. It is however something everyone that implements the stack in an existing project will bump into, and it certainly took me a while (and some guidance by the ever helpful Aras) to figure out why our other seemingly unrelated effects weren't working properly anymore. 

Perhaps its possible to show a warning when overwriting the depthtexturemode if the original is not what is expected. At least that way you can point the programmer in the right direction.

**Comment by JohannesDeml** [comment]
Since the problem still exists and I myself have it as well, I wanted to ask what you think of my solution:
- A simple new tab like the other in which you can set external requirements (Right now only the camera mode). This tab does not change the checking of camera mode requirements of activated effects, but just add itself as another requirement. I already implemented the script on my stack:
![externalrequirements](https://cloud.githubusercontent.com/assets/4518980/22626920/f14940d0-ebb7-11e6-8d6e-34e92c750043.PNG)

The stack is already a bit different in functionality, that's why I'm not sending a pull request. I'm interested if you like the take on the problem? If so I would implement my solution from your repo.

**Comment by Chman** [comment]
See #173.

We decided to simply "leak" camera depth texture modes for now, just so the stack can live next to other existing effects (Asset Store etc). "Leak" is probably not the correct word in this case, as I can't imagine a game where you'd want to keep enabling & disabling effects that require depth & motion vectors. Effects are generally always on and if you never use an effect that requires depth then it won't be enabled anyway (note that motion vectors require depth, so as soon as you enable TAA or Motion Blur you will need both buffers anyway).
