### ISSUE TITLE
[V1] Uber.shader is 11.3 mb in the game build

### ISSUE THREAD

**Issue by andrew-grischenko** [Unity-Technologies/PostProcessing#333]
I'm using Post-processing stack version v1 to apply "Bloom" effect to my camera.

When I build APK for Android, the largest file in the build is the "Uber.shader" occupying 11.3Mb of the build (33% of my app space). Is it a bug? How can I reduce that monstrous size?

**Comment by andrew-grischenko** [comment]
@Kink3d Do you have any update on this please?

**Comment by Chman** [comment]
This is due to the amount of variants in the Uber shader v1. The only way to reduce its size is to comment or remove the shader variants you don't actually use. See [this section](https://github.com/Unity-Technologies/PostProcessing/blob/v1/PostProcessing/Resources/Shaders/Uber.shader#L22...L29) of the file. For instance if you don't use the bloom dirt texture you can delete `BLOOM_LENS_DIRT`. Or if you don't need depth of field, you can remove the whole line. Removing what don't use will dramatically reduce the number of variants and thus the final file size.

**Comment by esalberg100** [comment]
It is a bug, however I doubt it will be fixed anytime soon.

**Comment by khalv** [comment]
@Chman Would it not be possible to add something like this:

```
#ifndef _STRIP_CHROMATIC_ABBERATION
#pragma multi_compile __ CHROMATIC_ABERRATION
#endif
```

To all the multi_compiles? Then you can add some custom scripting define symbols in the player settings to enable/disable features. Or do these not work for shaders?
