### ISSUE TITLE
[V1][V2] TAA doesn't support camera with a custom projection matrix.

### ISSUE THREAD

**Issue by Teshla** [Unity-Technologies/PostProcessing#376]
If you set a custom projection matrix before TAA is executed, it doesn't take that matrix into account. It would be helpful if it would use the currently set camera matrix for jittering and TAA calculation.

**Comment by Chman** [comment]
It does support custom projection matrices but you have to provide the jitter matrice yourself because we can't really jitter any kind of matrice in a generic way.

See the following delegates:
- [v1](https://github.com/Unity-Technologies/PostProcessing/blob/v1/PostProcessing/Runtime/PostProcessingBehaviour.cs#L19) (takes a `Vector2` jitter offset and returns a jittered `Matrix4x4`)
- [v2](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Runtime/Effects/TemporalAntialiasing.cs#L25) (takes a `Camera`, a `Vector2` jitter offset and returns a jittered `Matrix4x4`)
