### ISSUE TITLE
[V2] Anamorphic bloom is broken in latest versions

### ISSUE THREAD

**Issue by CustomPhase** [Unity-Technologies/PostProcessing#378]
Heres anamorphic bloom using the version from a month ago:
![old](https://user-images.githubusercontent.com/10864826/33370286-ec156210-d518-11e7-8307-7395b41940f3.PNG)
Heres anamorphic bloom with the latest (29.11.2017) version:
![bug](https://user-images.githubusercontent.com/10864826/33370334-0c8ef8a8-d519-11e7-9190-ddddd0bdc4d1.PNG)
Same settings, same project. Literally just replaced the asset files. As you can see, it doesnt make it anamorphic at all. Unity 2017.2.0f3, DX11, Win7, GTX1050 TI.

As a side note, can we get an ability to go higher than 1 on anamorphic ratio? To get more of a streak effect.

**Comment by Chman** [comment]
I pushed a fix for this in 9ed158c.

As for pushing the parameter higher than 1 to get streaks, no, it would be too expensive and anamorphic lens effects aren't the same thing as streak effects. Streaks should have their own effect. Eventually we'll add one to the stack because it would be a nice feature to have for sure.
