### ISSUE TITLE
Androdi build of empty scene creates 56k bin files in ShaderCache folder

### ISSUE THREAD

**Issue by Bzucko** [Unity-Technologies/PostProcessing#39]
Reproduction steps:
- create new project
- switch to android platform
- import post process package into assets folder
(project settings:
-graphics api only openGLES3
-min. api level 19
-device filter only ARMv7
-stripping level: use micro mscorlib
)
- build apk locally

First build process takes almost 8min....longest part is shaders compiling, which creates 56674 bin files in Library/ShaderCache folder. Are all those files necessary or better question do I need all files from post proces package import into project folder for full functionality?

In other architectural scene after few test, changes and builds, ShaderCache folder contains 150k+ files and it takes me 20min to delete them all. Thanks for any info and answer ;-).

unity 5.5.0p1
post process beta4
Xeon E3-1231v3

**Comment by Chman** [comment]
These are shader combinations mostly used to optimize the post-fx uber shader (so if one effect is disabled at one point in time, it'll switch to a shader version that doesn't have the code for this effect so it doesn't have to compute it for nothing and waste precious GPU cycles).

Because the uber shader has a lot of variations it can slow down the first build unfortunately... Subsequent builds should be fast though, unless you're building from scratch every time.

We're evaluating alternatives to avoid long built times in the future.
