### ISSUE TITLE
Custom Post Processing effects does not export

### ISSUE THREAD

**Issue by bonzajplc** [Unity-Technologies/PostProcessing#397]
Yep :), this can be easily reproduced with Grayscale example. 

Current workaround is to:

1. Change the shader classification to not Hidden
2. Attach the effect to a dummy mesh on the scene
3. Disable the mesh (exporter will export the material)
4. It works now.

Other than that it fails on line:

`var sheet = context.propertySheets.Get(Shader.Find("Hidden/Custom/Grayscale"));
`

**Comment by Chman** [comment]
That's not a post-processing issue, you have to tell Unity that you want the shader to be bundled in the build, either by using the `Always Included Shader` list in `Edit -> Project Settings -> Graphics` or put your shader in a `Resources` folder. Else it'll strip it because no reference exists in any scene so it considers that it's not used at all.

**Comment by bonzajplc** [comment]
Ah, I'm such a Unity noob :). Thanks for the info. Hopefully other issues are not the same examples of my ignorance :)
