### ISSUE TITLE
noiseTex: Argument cannot be null

### ISSUE THREAD

**Issue by AberrantWolf** [Unity-Technologies/PostProcessing#403]
I'm getting the following error exception frequently during updates:

```ArgumentNullException: Argument cannot be null.
Parameter name: value
UnityEngine.MaterialPropertyBlock.SetTexture (Int32 nameID, UnityEngine.Texture value) (at C:/buildslave/unity/build/Runtime/Export/Graphics.cs:475)
UnityEngine.Rendering.PostProcessing.Dithering.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing-2/PostProcessing/Runtime/Effects/Dithering.cs:31)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.RenderFinalPass (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context, Int32 releaseTargetAfterUse) (at Assets/PostProcessing-2/PostProcessing/Runtime/PostProcessLayer.cs:901)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing-2/PostProcessing/Runtime/PostProcessLayer.cs:694)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at Assets/PostProcessing-2/PostProcessing/Runtime/PostProcessLayer.cs:432)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Assets/PostProcessing-2/PostProcessing/Runtime/PostProcessLayer.cs:294)
```
When I debug this in Visual Studio, I can see that the value `noiseTex` is indeed null, as are all values inside the `blueNoise` array acquired from context.resource.nblueNoise64.

**Comment by Chman** [comment]
There should be a `PostProcessResources` file in the `PostProcessing` folder, could you check that the `Blue Noise 64` and `Blue Noise 256` arrays are properly populated and don't have null elements? It could be that the meta for this file got trashed while updating and thus loses reference to the noise textures.

**Comment by dvanhaazel** [comment]
@Chman I had the same problem with one of my projects. Multiple other projects with same version didn't give me any problems. But I did a trace and saw in the debugger the arrays in the m_Resources were filled but all null. So it seemed the PostProcessResources weren't loaded properly for some reason. 

I solved it by adding a forced load in PostProcessLayer.cs inside the Init method:
 ```
 public void Init(PostProcessResources resources)
        {
#if UNITY_EDITOR
            m_Resources = (PostProcessResources)UnityEditor.AssetDatabase.LoadAssetAtPath("Assets/PostProcessing/PostProcessResources.asset", typeof(PostProcessResources));
            m_Resources = PostProcessResourcesFactory.Stripped(m_Resources);
#endif
```

maybe a good thing to just always load the asset resource instead of hoping unity will pick it up properly for automated deserialization ?

**Comment by Chman** [comment]
Yeah it's clearly a serialization bug with Unity itself and that's unfortunate. It's been reported but it's hard to reproduce as it seems so random.

The problem with loading it the way you do is that it doesn't work with the package manager and won't work if the user moves the PostProcessing folder to another location when not using the package manager - so in versions pre-2018.1 - unless we do a search for the file first etc etc but that's a lot of boilerplate code _we shouldn't even need in the first place_. So the best course of action would be to actually track down the issue in Unity and fix it at its source instead of introducing yet another workaround :(

**Comment by Chman** [comment]
> Maybe it's no issue any longer when the project gets imported through the package manager instead of a manual Git download?

That's my experience but it's hard to say at this point until more people use it.

> Any idea when v2 gets out of beta and available through the asset store?

It'll be out of beta for 2018.1 and will be distributed via the package manager (and will be enabled and setup by default in some of the templates we provide with the new launcher - already available in 2018.1 beta). We won't distribute it on the asset store anymore, "official" packages & features will go through the package manager as it makes it easier for us to update them quickly, have different branches ("stable", "latest", etc) and is also easier for users (tightly integrated with Unity, no need to go through the asset store to grab it etc).

**Comment by Chman** [comment]
Note: we removed the automatic resources stripping process, the previously posted hack isn't necessary anymore. If you have a `PostProcessResourcesUnstripped` asset in your project you'll have to update to the latest version and recreate your PostProcessLayer component for the fix to be applied.

**Comment by Pikachuxxxx** [comment]
I had the same issue in 2019.3.0f6, reimporting back fixed it anyways thanks for the solution maybe it'll help me someday. It's weird that this still exists.
