### ISSUE TITLE
Min and Trackball not found

### ISSUE THREAD

**Issue by aaperesc** [Unity-Technologies/PostProcessing#409]
Assets/PostProcessing/Runtime/Effects/AutoExposure.cs(27,10): error CS0246: The type or namespace name `Min' could not be found. Are you missing an assembly reference?

Assets/PostProcessing/Runtime/Effects/ColorGrading.cs(128,89): error CS0246: The type or namespace name `Trackball' could not be found. Are you missing an assembly reference?

**Comment by ubiko** [comment]
Same issue here

**Comment by Chman** [comment]
The only way this can happen is after a faulty import of the PostProcessing source code or if you already had compilation errors before you tried to import PostProcessing (these will stall the compilation pipeline and output more errors due to new scripts not being imported correctly). The reason why it "works" by upgrading to 2018 beta is because moving to a newer version of Unity will force re-import everything.

In cases like this, the solution is to right-click on the PostProcessing folder and select "Reimport". Make sure the rest of your project compiles fine before doing that and you don't have any other remaining error.

**Comment by maguslin** [comment]
reimport will not work actually.my version is 2017.2.0f3,there's no unity package file for me to import ,the only way I can do is copy the whole folder into my asset ,however, It's not work

**Comment by maguslin** [comment]
still the same issue

**Comment by onesimusrex** [comment]
I'm having the same issue too.

**Comment by dmm-pete** [comment]
Same here. Even did a "Re import all". The errors won't go away. Unity 2017.2.0f3.

**Comment by Torantulino** [comment]
Same issue here still 2017.4.18f1 LTS
