### ISSUE TITLE
Why is AA on the layer and not an added effect?

### ISSUE THREAD

**Issue by shaderbytes** [Unity-Technologies/PostProcessing#428]
So I am busy upgrading some code for using PostProcessing 1 to now use 2 and Unity 2018.1beta.

In the process while learning about volumes and cloning and overriding I noticed AA is not an added effect of a volume profile , but is an instance on the camera layer.  There is obviously some clever reason why this is so but in regards to usability it is not great.

In My previous code I had some menu options to disable certain post process effects.

Bloom
AmbientOcclusion
ChromaticAberration
AA

As you can now see AA is not an added profile effect and i cant simply enable/disable this now as the others.. i have to handle is separately in a complete different manner. Maybe unavoidable due to the nature of the set up, but maybe a default proxy setting on the profile that just points to this? then it will look like a setting residing in the same place and the code will not look different to get it etc. It would also be nice to have an enabled/disabled property like the other settings.

**Comment by Chman** [comment]
AA is tied to the camera because there's really no point in having it in local volumes. The better reason is that AA is, in some cases, very dependent on the camera setup (TAA for instance will manipulate the projection matrix & requires specific handling in the render loop etc) and having these in volumes have too many implications and fail cases.

Overall, AA is a per-camera effect (if not per-game in most cases) and we don't have any plan to change this at this time.

As for your menu, even though it's a bit different it's not that much more difficult to handle (if anything it's easier). Grab the post-processing layer and set the `antialiasingMode` enum to whatever you want:

```
layer.antialiasingMode = PostProcessLayer.Antialiasing.TemporalAntialiasing;
```

I don't think antialiasing shouldn't be considered part of post-processing in an option menu (looking at most games these days they put AA on its own or next to general display settings) but that's just my opinion :)

**Comment by shaderbytes** [comment]
one thing to note i could not grab the layer via get component on the camera, i had to create a field for it and drag the camera on it in the inspector.

**Comment by shaderbytes** [comment]
mm.. maybe my camera was disabled or something. I do recall my codebase does disable the camera at startup, it must be that then. Thanks for the clarification and confirmation. Since i need to have my camera disabled i guess having an inspector reference then is the only way.
