### ISSUE TITLE
TAA not working on Vulkan

### ISSUE THREAD

**Issue by AubreyF** [Unity-Technologies/PostProcessing#457]
##### What happened?

See attached screenshot. Editor on left is running DX11. Build on right is running Vulkan. All other settings identical.

##### Post-processing stack version (v1, v2)?

v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity: 2017.3.0f3
OS: Windows 10 Pro
Graphics card: Nvidia 1080

![terra 2018-02-09 08 40 04_vulkan_vs_dx11_optimized](https://user-images.githubusercontent.com/2789037/36041479-80d60fc0-0d7d-11e8-8c88-7068c7314544.jpg)

![terra 2018-02-09 08 40 04_vulkan_vs_dx11_tight](https://user-images.githubusercontent.com/2789037/36041642-0a1ee78e-0d7e-11e8-8e49-7a21244194b0.png)

**Comment by Chman** [comment]
Vulkan is still experimental but for what it's worth, I just ran a test in 2018.1.0b10 and TAA seems to work fine there. Considering that this target is still in heavy development I wouldn't be surprised if the issue you're experiencing got fixed along the way.

Also please note that it's hard to see any difference on your screenshot due to the nature of what's on the screen and the fact that it's a compressed jpeg with artifacts.
