### ISSUE TITLE
Colorgrading with 2D LUT gives wrong colours

### ISSUE THREAD

**Issue by WispBart** [Unity-Technologies/PostProcessing#490]
##### What happened?
I've been using AmplifyColour and would like to transition to PostProcessingStack v2 for the next big version of my project. This means I already have a whole bunch of LUT textures that I would prefer not to have to re-author. 

My assumption was that LUT textures would always be applied in the same way, meaning that I would be able to use my old LUTs with any color grader and the result should be the same. PostProcessingStack v1 also gives the same result. Unfortunately this is not the case with PostProcessingStack v2. Beyond it being different, the PPS v2 version also looks decidedly worse.

This leads me to believe that this is the result of a bug in the PostProcessingStack v2 colorgrading component.

Here's a screenshot of the differences, using a LUT that clearly displays the difference.
![amplifyvspostprocessing](https://user-images.githubusercontent.com/17644115/36970099-acd3f39c-2067-11e8-86d6-89154c3de9ab.png)
(I added the PPS v1 screenshot later, the difference between it and AmplifyColour such as the missing rimlight are probably a result of different test setup settings)

##### Post-processing stack version (v1, v2)?
PostProcessingStack v2 (commit 3e5346af8229c3792a6c0011b8929daec159ea67, Mon Feb 19 13:35:56 2018)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.3.1f1, Windows Editor.

**Comment by Chman** [comment]
Ha, I wonder how it stayed unnoticed for so long... I just took a peek at the code and there's in fact a color space issue in v2 when the LDR 2D-strip LUT is applied. Basically, the lookup is done in linear instead of sRGB which results in the color shift you're getting.

It's fixed in [this branch](https://github.com/Unity-Technologies/PostProcessing/tree/ldr-lut-srgb). Could you try it and report back before I merge it?

**Comment by WispBart** [comment]
Looks fixed to me! Thanks!

**Comment by Chman** [comment]
Merged!
