### ISSUE TITLE
[V2] SSR not detailed like v1

### ISSUE THREAD

**Issue by ghiboz** [Unity-Technologies/PostProcessing#505]
##### What happened?
Hi, I'm using all the V2 PP into my project, but I noticed that the Screen Space reflection is very bad compared with V1:
here is a shot of the actual V2 set to maximum
![v2](https://cdn.discordapp.com/attachments/342772804053237782/425776668469362689/Unity_2018-03-18_13-11-34.png)

and this is the same scene with the old SSR of the v1
![v1](https://cdn.discordapp.com/attachments/342772804053237782/425776647824998401/Unity_2018-03-18_14-02-27.png)

##### Post-processing stack version (v1, v2)?
V2, and seems also that V1 was more powerful

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.3.1f1, windows 10 64

thanks!!

**Comment by Chman** [comment]
As per the [documentation](https://github.com/Unity-Technologies/PostProcessing/wiki/Screen-space-Reflections):

> The current implementation of Screen-space reflections in Unity is tuned for performance over quality to make it usable in production on current-gen consoles and desktop computers. Be aware that this technique isn't meant to be used to get perfectly smooth reflections, you should use probes or planar reflections of that. This effect is also great at acting as a specular occlusion effect by limiting the amount of specular light leaking.

V1's implementation was really, really slow. To the point of being barely usable in production and completely out of the question on consoles. I'm talking 15ms+ on PS4 slow here. Current V2 implementation is much, much faster, even though we're quite limited by what can be achieved in the Standard Render Pipeline when it comes to the speed/quality ratio of such an effect (the HD Render Pipeline will get a custom, tightly integrated SSR implementation at some point).

Also let me emphasis that SSR should not be used on perfectly smooth surfaces. It's meant for rough surfaces (where lower quality and artifacts due to being a screen-space effect are not visible anymore). Trying to do a mirror plane with SSR won't work.
