### ISSUE TITLE
MSVO lacking overlay mode

### ISSUE THREAD

**Issue by hippocoder** [Unity-Technologies/PostProcessing#540]
Hello!

I wondered if I was using it wrong, but for a large portion of projects which use stylised rendering, MSVO settings would benefit from an overlay mode - ie entirely ignoring the lighting in the scene, for clay, cartoon, NPR rendering.

Please consider otherwise these projects will require a non-optimised solution and possibly even falling back to builtin instead of using preferred HD.

**Comment by Chman** [comment]
I'm not sure I understand. Are you talking explicitly about how MSVO is applied on HD? Because on vanilla/builtin you can apply AO as-is without any regard for the current lighting by not setting Ambient Only.

If it's an HD-specific question then you should know that HD only relies on post-processing to request a raw AO map from a given depth map and then applies it during its lighting pass (side note: as it should be, instead of being considered a post-processing effect). They do that for multiple reasons (correctness, avoiding "double AO" with material AO and lightmap AO etc). If that's what you're talking about then I would open a topic in the SRP repository to discuss it. I'm not entirely sure how feasible it is to expose such an option in HD considering the implications but you never know!

**Comment by hippocoder** [comment]
Thanks for explaining, it was very helpful :)
