### ISSUE TITLE
Unable to choose when to execute the command buffer during rendering

### ISSUE THREAD

**Issue by jimmikaelkael** [Unity-Technologies/PostProcessing#547]
I'm currently trying to convert my HBAO asset to use the PostProcessing v2 as a custom effect however I can't find anywhere in the docs how to choose when to execute the command buffer during rendering.

I need to let my customers choose between BeforeImageEffectOpaque, BeforeReflections or AfterLighting.
No really sure it's an issue but if anyone can help I will appreciate it.

I've seen this is done in the PostProcessLayer script but how a custom effect will do that ?

**Comment by Chman** [comment]
The injection points are currently static and defined in the effect attribute. One of the commit in #530 (389051) adds support for runtime event selection but this is still being reviewed.

**Comment by jimmikaelkael** [comment]
You are talking about PostProcessEvent. I was talking about the CameraEvent used by the command buffer, is there a relationship between the two I'm not aware of ?

**Comment by Chman** [comment]
Ah, right, sorry. I misread.

Then no, you can't choose a custom `CameraEvent` for the command buffer. Porting lighting/surface effects to v2 is not going to be easy without adding custom code into the layer component as they have their own specific requirements and the current framework is really made with post-processing in mind (AO isn't a post-processing effect per-say, even though it's currently bundled with the stack, it actually used to live on the side a few months ago).

So your best bet really is to keep it as a standalone component that manages its own command buffer so that you have complete control over how your effect is being rendered. The only downside is that you won't be able to benefit from the volume system, but in the case of AO it's rarely an issue to be honest, blending AO radius or quality between volumes isn't common practice in production.

**Comment by jimmikaelkael** [comment]
I see, it perfectly makes sense. Thanks for the explanation @Chman!
Don't take it as a complaint but the worst part will be to explain that to customers (some of them already asked me if it was possible to port HBAO to it)...  
I already hear them say things like "how you can't do that, Unity made it" 😄
