### ISSUE TITLE
[V2] Interface for configuring image effects feels less intuitive than V1

### ISSUE THREAD

**Issue by oyvind-stromsvik** [Unity-Technologies/PostProcessing#560]
##### What happened?

In V1 you have all the effects listed in a fixed order that is the same between all your projects and the interface looks more consistent with the rest of Unity. And effects are either enabled or disabled clearly indicated by the checkbox next to each effect.

In V2 when you create a profile it's empty and you have to add each effect to it individually, but when you do the effects are listed in the order you added them and not in a fixed order, nor is it possible to reorder the effects. And the list itself has a look unlike anything else I've seen in Unity. I have to assume the V1 look is "native" because that's a look shared by a lot of Asset Store assets. 

And there's seemingly multiple states for each effect rather than just enabled/disabled. An effect can not be added to the profile, it can be added, but unchecked, it can be added, checked, but set to "OFF", it can be added, checked, set to "ON", but not overridden and the default intensity is 0 so it's essentially disabled. This seems more confusing than it has to be in my opinion.

I also have some gripes with the way the effects defaults are presented and how you override them, but I understand that V2 is more advanced than V1 and I don't really have any good ideas on how to present this part differently. I feel like more contrast change between the different states would improve the look of it at least, there's like 10 similar shades of gray used here at the moment.

##### Post-processing stack version (v1, v2)?

Version 2.0.5-preview, but has been the case for V2 always.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2018.1.0f2, Windows 10, Windows, but this is editor related and this has been the case with V2 always.

**Comment by Chman** [comment]
> In V1 you have all the effects listed in a fixed order that is the same between all your projects and the interface looks more consistent with the rest of Unity. And effects are either enabled or disabled clearly indicated by the checkbox next to each effect.

v1 was fully static, hardcoded, hard to animate and non-extensible. v2 fixes all of that and is based on a volume framework. I'd recommend reading #456, #208 and [this comment](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Runtime/PostProcessVolume.cs#L5..L52) for more insight on what it means and why it's like that. As for interface consistency, see below.

> In V2 when you create a profile it's empty and you have to add each effect to it individually, but when you do the effects are listed in the order you added them and not in a fixed order, nor is it possible to reorder the effects.

Because there's no need to reorder anything, effects are ordered automatically for best use no matter how it looks in the UI. Granted, we could certainly add a way to reorder the list just to make it nicer.

> And the list itself has a look unlike anything else I've seen in Unity. I have to assume the V1 look is "native" because that's a look shared by a lot of Asset Store assets.

v1 wasn't native, v1 was the first feature to use this styling (derived from Shuriken) and it got used afterward by a lot of assets. And it's the same for v2. The v2 style is being reused a lot (especially on [SRPs](https://github.com/Unity-Technologies/ScriptableRenderPipeline)) and is derived from the Audio Mixer.

> And there's seemingly multiple states for each effect rather than just enabled/disabled. An effect can not be added to the profile, it can be added, but unchecked, it can be added, checked, but set to "OFF", it can be added, checked, set to "ON", but not overridden and the default intensity is 0 so it's essentially disabled. This seems more confusing than it has to be in my opinion.

This is a volume/override system and that's how it works in most game engine. You _need_ these features. But I am of course opened to any kind of UX improvement that doesn't affect the feature-set :) But considering all the implications it's not an easy task, and so far this is the best we could come up with. If you have any suggestion please don't hesitate to write them down!
