### ISSUE TITLE
360 Capture Bloom

### ISSUE THREAD

**Issue by SmarterPhoneLabs** [Unity-Technologies/PostProcessing#565]
##### What happened?
Bloom presents odd behavior on 360 rendering with Camera.RenderToCubemap()
I am the author of the capture tool called Helios.
Since the release of the Post Processing tools I have noticed this but think I now have narrrowed the issue down to Bloom.

As you can see from the 2 images shown below, one with bloom on and one with bloom off.
If you look at the area on the floor you can see the bottom camera produces some reveresed bloom effects.

##### Post-processing stack version (v1, v2)?
1.0.4

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018 1.0.f2
Editor Only builds right now.
![img00396](https://user-images.githubusercontent.com/1190629/40142540-89ea3194-591e-11e8-9a78-00c68f99214c.png)
![img00397](https://user-images.githubusercontent.com/1190629/40142542-8bf1510c-591e-11e8-9050-b82f6204924f.png)

**Comment by rsodre** [comment]
Looks like it happens where the cubemap faces connect.

**Comment by Chman** [comment]
This is not something that can be easily fixed. As @rsodre pointed, this is due to the fact that cubemaps are created by doing 6 renders of a camera rotated by 90deg increments and bloom doesn't have any knowledge of "neighbor" cubemap face textures.

With that said, 360 captures are typically done _without_ post-processing and post is applied _after_, when rendering the 360 on screen. This is the only reliable and fast way to make it work with any kind of diffusion effects (bloom, DOF, motion blur and the likes). So you should disable postfx when capturing the cubemap and only enable it when rendering.
