### ISSUE TITLE
[V2] Is anyone at all able to use SSR in its current state?

### ISSUE THREAD

**Issue by oyvind-stromsvik** [Unity-Technologies/PostProcessing#569]
##### What happened?

This: https://github.com/Unity-Technologies/PostProcessing/issues/368

I'm honestly wondering if there's something I'm doing wrong here based on this reply (https://github.com/Unity-Technologies/PostProcessing/issues/368#issuecomment-346658129) in the above thread:

> For most use cases this works just fine.

How? I'm fiddling with a project right now where I have a third person character in a corridor with reflective surfaces all around and every single reflection is 100% wrong, just like in the example shown above. The character's hands are creating streaking reflections on the floor, there's a halo around the character, the entire character is creating streaking reflections on the floors, walls and ceiling. I consider it 100% unusable at the moment.

I don't know anything about what goes into such an effect, but I haven't seen these artifacts in any production game, nor do I understand how they occur or how they are deemed to be acceptable. My expected result from using SSR is that what I can see on screen is reflected in reflective surfaces, not that they reflect stuff that isn't there.

##### Post-processing stack version (v1, v2)?

Version 2.0.5-preview.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2018.1.0f2, Windows 10, Windows, but I'm mostly testing in the editor.

**Comment by artyom-zuev** [comment]
I have to agree, streaking artifacts are a big issue in any scene with overhanging object shapes (street lights, characters, vegetation). I'm currently actively avoiding screen space reflections unless my scene is filled with something like simple boxes, which is unfortunate. I vaguely recall earlier implementations of SSR (not sure if that was PostProcessing v1 or Cinematic pack) not having that issue, would be wonderful to get that back.

**Comment by Chman** [comment]
Merging with #368. Somewhat related, see the reply to #505.

**Comment by oyvind-stromsvik** [comment]
Not to be rude, but I don't feel these issues are related at all. My issue has to do with seemingly unavoidable artefacts apparently stemming from a performance-shortcut in the current SSR implementation while he's wishing for mirror like reflections.

I feel like my question still stands: Is anyone able to get acceptable results from the current SSR implementation? I've tried it in all my projects, but the artefacts it has makes it unusable in any of my scenarios. I will provide example projects if it's still unclear what I'm talking about.

And your reply to the other isssue is one of my current gripes with the post processing stack V2. Most of the effects basically only have an on/off toggle with barely any options for tweaking the effect. What if we want mirror like reflections from our SSR even though it's extremely non-performant? Maybe it's for a still image or for a rendered video? Or maybe we want to use an effect for a purpose it wasn't meant for, but it's exactly what we're after? If these options require completely different implementations of the effects then I agree they are outside the scope of the project, but I feel like a lot of them just has to do with clamped values or options that aren't made available to us in the inspector.

One example being the bloom I mentioned here https://github.com/Unity-Technologies/PostProcessing/issues/559 where it's hard-coded to work on a downscaled buffer. Why not present this option in the inspector? Let us choose the performance/quality setting ourselves. Maybe a quarter size is enough for certain projects or maybe full size is required for others? Personally with the current blur algorithm I feel full sized is required to avoid a lot of the "wobbling" which I personally find very off-putting.

Another example is the SSAO where I've previously used SSAO Pro which I believe is developed by you which comes with a plethora of options whereas the one in the post processing stack is basically on/off. There are a lot of things that I feel like I'm unable to reproduce with the SSAO in the post processing stack that I was able to do with SSAO Pro. And in one project I used SSAO Pro for tight occlusion and HBAO (from the asset store) for broader occlusion which I feel gave very pleasant results, maybe not very performant, but it gave me what I wanted.

In general I just hope that you can support a lot more workflows with the post processing stack rather than just what's considered standard or best practice, at least if these things only require you to expose a few more options to us.

I know that it's open source and that we can work on it ourselves, but I lack the skills necessary to do a lot of these things as do most people I would assume, and it also makes the whole package manager / official asset thing a bit of a hassle if we have to use a custom version of the asset to get what we want.

**Comment by Chman** [comment]
> Not to be rude, but I don't feel these issues are related at all. My issue has to do with seemingly unavoidable artefacts apparently stemming from a performance-shortcut in the current SSR implementation while he's wishing for mirror like reflections.

How is this different from #368 ? You even linked it in your original post, this is the exact same issue you're describing. I closed this one and marked it as a duplicate because it is exactly that, a duplicate, there's no need to open another issue when there's already one that exists and is still opened. This is not a forum, it's an issue tracker :)

> Most of the effects basically only have an on/off toggle with barely any options for tweaking the effect.

This is dishonest considering how many settings there are and that most users don't even use a quarter of them. Give me a list of settings you want for all the effects then. But we can't expose every little settings you'd want for a multitude of reasons (performance, maintenance, bandwidth). But the good thing is, this package is free & open source. Grab it, fork it, tweak it. It's meant to be if you need heavy customization.

> If these options require completely different implementations of the effects then I agree they are outside the scope of the project

They do require completely different implementations. It's not as easy as you think it is, really.

> What if we want mirror like reflections from our SSR even though it's extremely non-performant?

You seem to misunderstood how SSR works. Even with a perfect SSR implementation you _can't_ have mirror reflections. You can't reflect something that doesn't exists on the screen in a screen-space effect. If you don't believe me look closely at other engines & games that shipped with SSR (and make sure you're looking at SSR and not planar or probe reflections). I'm not saying ours is good by any mean though. But somehow a lot of people think of SSR as being "magic" when it's just a very bad trick.

> [...] SSAO [...]

Come on now, I see more settings than "on/off"... And MSVO is way higher quality and wider than SSAO Pro, not to mention how fast it is. You have to remember that this is a game engine first, it is meant for real-time use. You'll never see a game with multiple variants of SSAO algorithms stacked on top of each other as it would be under performing.

> In general I just hope that you can support a lot more workflows with the post processing stack rather than just what's considered standard or best practice, at least if these things only require you to expose a few more options to us.

We plan to and I _want_ to, believe me, I've been pushing for this kind of stuff but v2 is currently held back by a lot of considerations I couldn't even begin to list (having to support 15 billion platforms is one of them). v2 is generic, it's meant to work almost everywhere and give a nice post-processing framework to use. The stack is specific to a single game unfortunately so we don't have the luxury of going crazy with settings & quality. If it were up to me I would've gone full compute & AAA as minimum spec a long time ago but, you know, priorities :)

**Comment by oyvind-stromsvik** [comment]
> How is this different from #368 ? You even linked it in your original post, this is the exact same issue you're describing. I closed this one and marked it as a duplicate because it is exactly that, a duplicate, there's no need to open another issue when there's already one that exists and is still opened. This is not a forum, it's an issue tracker :)

Sorry, I absolutely missed that part. I only saw the reply to the other closed issue and felt like you brushed it off. My bad.

I know this isn't a forum, but is there a place more suited for discussion around version 2 of the post processing stack? When I google this is where I end up. And at work we usually have labels like "question" etc. for things that aren't todos on github. I usually have a lot of opinions about how I feel things should work, but I'm not very skilled when it comes to technical/graphical programming. :) A lot of the stuff I'm talking about or asking about here are just naive questions.

I'll make specific issues if there are settings I feel makes sense for us to be able to tweak, and I'll try my best to look at the code and see if it would actually be feasible beforehand. I have no presumption of anything being easy, and certain settings may be hidden because showing them makes no sense as they have no noticeable impact on the end result anyway, but that's why I'm trying to get an understanding as to why things are the way they are.

I want to use the gaussian bloom wobble fix in all my projects so I'm beginning to accept the fact that I will never be able to use the post processing stack straight from the package manager anyway based on your reply to that issue. :) 

Anyway, thanks for taking the time to write such a thorough reply. I won't bother you any more here.
