### ISSUE TITLE
why "Uber.shader" is so big?

### ISSUE THREAD

**Issue by iniwap** [Unity-Technologies/PostProcessing#583]
##### What happened?
Used Assets and files from the Resources folder, sorted by uncompressed size:
 7.6 mb	  Assets/PostProcessing/Resources/Shaders/Uber.shader

**Comment by Chman** [comment]
7.6MB uncompressed isn't what you'd consider "so big"... It's because of [all the permutations](https://github.com/Unity-Technologies/PostProcessing/blob/fe9d5f532e4a70649f996bcb317f5aae27efde0d/PostProcessing/Shaders/Builtins/Uber.shader#L7..L13), for performance reasons (size vs speed). You can remove the ones you don't need if you truly want to reduce the size. Keep in mind that the size you listed is the _uncompressed_ size.
