### ISSUE TITLE
DLAA would be a useful option to have for Anti-Aliasing.

### ISSUE THREAD

**Issue by dbastien** [Unity-Technologies/PostProcessing#584]
Unity used to support this, and it has some nice temporal stability properties.

**Comment by Chman** [comment]
We don't have any plan to maintain more anti-aliasing solutions to the stack at this point, only to improve the current ones. The cost/quality ratio of DLAA is also not very interesting compared to other solutions. For what it's worth, extracting DLAA from the very old image effects and adding it to v2 as a custom effect shouldn't be too hard.

**Comment by dbastien** [comment]
Fair!  Yeah I'll throw it in as a custom effect for sure.

It's a weird situation where we're a card game (MTG Arena) with tons of
straight lines everywhere and I was thinking DLAA might be an interesting
option because it has some decent temporal stability properties.

**Comment by Chman** [comment]
If you ever make a custom effect out of it don't hesitate to share it on Github, if it works well for some use cases compared to SMAA or TAA I'm sure other people will be interested in it!

**Comment by dbastien** [comment]
Would there be some perf benefit to integrating it in directly?  
I imagine there's some gains to having it as part of the uber block?
I mean as far as sharing did you mean in another repo or submitted as a PR?

**Comment by Chman** [comment]
IIRC DLAA is a multi pass algorithm so there won't be much benefit from integrating it directly as opposed to using a custom effect. We don't do any AA in the Uber block because it's actually faster to do it separately in our case with all the neighbor sampling effects we have (saves a metric ton of bandwidth and ALUs).

By sharing I just meant put it somewhere on Github as a custom effect, not as a PR :)

**Comment by dbastien** [comment]
​Yeah no worries if there's no perf benefit to​ doing it in the uber block
- I'll do as you suggest and do the regular custom effect thing.

Thanks!
