### ISSUE TITLE
Referring in-scene object from settings

### ISSUE THREAD

**Issue by RamiroOliva** [Unity-Technologies/PostProcessing#594]
GameObjectParameter doesn't seem to accept scene objects. I wrote a custom editor and it only allows to pick gameobjects from the project but not from the scene. Is there any special setting or workaround?

**Comment by Chman** [comment]
That has to do with the fact that post-processing profiles are assets and you can't currently link scene-referred objects in assets in Unity, not from the editor anyway (it's possible at runtime via scripting). I'm afraid that for this one we'll have to wait for Unity to support this feature.

**Comment by Chman** [comment]
I'm curious, what would you need access to the serializedObject for?

**Comment by RamiroOliva** [comment]
Mostly because I need a reference to the settings component used by the PostProcessingVolume.
On one hand we have the scriptableObject for profiles but when you have PostProcessingVolume component you can override some properties. In this case I'd like to set some scene dependant references which will be used by the render script.

**Comment by RamiroOliva** [comment]
I've found that if I define a SerializedProperty, I can get the reference to the target using:

SerializedProperty sun;
...
sun = FindProperty(x => x.sun);

then

sun.serializedObject.target

Problem is the settings component does not persist. Still figuring out what the best way to achieve this. Basically I want to reference an scene light from the settings component but for some reason it does not get saved.

**Comment by RamiroOliva** [comment]
Yuk! I see where the problem comes from!

So the "Overrides" section shown in Post Process Volume inspector is just the same profile! Any change I make to this editor goes to the same profile asset so it was not working as I thought initially.

With "Overrides" (the label shown on top of the settings under Post Process Volume) it seems like those settings will simply override the settings from the original profile. So I can reuse a base profile among different profiles and use the Overrides to add some change to each volume. However it looks like doing any change to the "Overrides" section just send the change to the same profile used by all volumes!

Is that the intended behaviour? Honestly, the Overrides label is really misleading..

**Comment by RamiroOliva** [comment]
Hi Thomas,

It’s misleading and I’ll explain why. I’m glad to contribute with a different perspective. Of course I’ll understand if you don’t change current behaviour.

It’s quite common to have different volumes where they simply vary one or two specific setting like those in Color Grading.

When I read "Override", coming from OOP, I expected a "virtual method approach" with the following workflow:
- Define one or more base profiles.
- Assign those base profiles to any number of Post Processing Volumes.

So...

a) If I want to introduce a change that will affect every volume, then I'd pick the corresponding base profile and modify it. Changes will affect all volumes that use them.

b) If I want to introduce a change that *only* affect one volume then I'd go to the specific Post Processing Volume, expand the Override section and specify there the changes I want for those volumes. The "override" term here references the fact that I'm overriding the base profile settings with custom settings for this volume. In no way those changes should be modifying the base profiles nor affect the rest of volumes.

With current approach, if I have 20 volumes and I want just subtle changes for them, I need to have 20 profiles, whereas using the approach described above it would only require 1 profile and specify the differences in each volume.

I hope this makes sense.

**Comment by Chman** [comment]
Sure, I understand where you're coming from and that would be one of the possible workflow for such a feature... if profiles were able to live in the scene, which they don't unless we break a few things along the way. The first v2 implementation was working in a similar way until we ran into a few Unity limitations (like the fact that this wouldn't work with prefabs at all, you can't store scene assets in prefabs, and other serialization issues). See [this comment](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Runtime/PostProcessVolume.cs#L6..L51) for a few more info about why it's like that.

So eventually we had to move to this "profile asset" design by technical necessity. With that said, I don't this as been very problematic, and I would argue that it's better in other cases like when you want to share the same set of overrides for different volumes to override a global one (just use the same profile instead of having to copy/paste all values and having to make sure you keep them in sync if you change one). Both ways of doing things have their pros & cons, but in this case we could only do one of them if we wanted to better integrate with other Unity features. And prefabs are hard to let go considering it's a feature everybody uses...
