### ISSUE TITLE
Motion blur sampleCount 

### ISSUE THREAD

**Issue by gambr** [Unity-Technologies/PostProcessing#596]
##### What happened?
Can sample cout be negative? If not, why an "int" is used instead of "uint"?
##### Post-processing stack version (v1, v2)?
v2

**Comment by Chman** [comment]
Sample count is positive. `int` instead of `uint` because of C# conventions & internal conventions (if it were up to me I'd use `uint` whenever I can but it causes more trouble than it's worth in C#), for the same reason you use `int` instead of `uint` in for loops when counting from 0 to whatever.

The sample count is clamped to `[1;64]` anyway so `int` or `uint` won't make a difference.

**Comment by gambr** [comment]
Hi Thomas,
I'm basically a C++ developer and I have to say that I prefer using iterators (c++ stl containers) or foreach (c#). Even when I have to use for loops I pefer using size_t (.e. unsigned int) instead of int at least in C++.
When I implement a method I use an unsigned int for non negative parameters because it is clearer for che caller and moreover I don't have to check for negatives (!). I don't understand when you say that "it causes more trouble than it's worth". Honestly, in this case, I have to cast esplicitly from uint (my interface) to int a parameter that indeed is an unsigned int. So, feel free to take your conclusions.

Regards,
Gianni

**Comment by Chman** [comment]
Like I said,

> if it were up to me I'd use `uint` whenever I can

for mostly the same reasons as you. But conventions are conventions, and there are more pressing issues than debating about the use of `uint` vs `int` ;)

> I don't understand when you say that "it causes more trouble than it's worth".

Almost all the APIs in Unity use `int` when they could use `uint` and because there's no implicit cast between `uint` and `int` it means having to cast everything all the time. And again, C# conventions... I mean, even `array.Length` and `list.Count` are `int`, so... Yeah :/
