### ISSUE TITLE
PPv2 does not work properly with HDRP and multiple camera's

### ISSUE THREAD

**Issue by shaderbytes** [Unity-Technologies/PostProcessing#636]
So im testing out HDRP , I have three cameras in the scene. Post process does not work properly unless i set the other two camera game objects to inactive.

I tried all sorts of layer changes , mask changes culling settings to no avail. This was not an issue when not using HDRP. The PP v2 works as it should with my cameras when using regular rendering.

Unity 2018.2.2.f1 Windows 10 64 bit 32GB ram 970 GPU i7 CPU

**Comment by shaderbytes** [comment]
here is video even for proof of this issue : 

https://www.youtube.com/watch?v=yefbbmnbgU4

**Comment by shaderbytes** [comment]
does anyone even read these issues .. seriously so many days with zero response? I even made a video to showcase the issue , do i need to beg? I will. Please can somebody from unity respond. I have tried every conceivable scenario possible , global/ non global , nothing and I mean nothing helps .. except changing the camera depth value.. but that is not an option as my custom UI needs to render above the game.. should I rather go post in the unity forums?

**Comment by Chman** [comment]
> does anyone even read these issues .. seriously so many days with zero response?
It's August, most people from Europe are on summer vacations. Slow response is expected at this time of the year.

As for the issue itself, it's an HDRP-specific issue with regards to how they handle multi-camera rendering. You should report it to the HDRP team. Side-note: instead of using two cameras and adding overhead to the render loop you should just set your UI canvas to Screen-space Overlay, it will automatically be drawn on top of the game without the need for a complex multi-camera setup.

**Comment by rlods** [comment]
I found and confirm the same issue. Post processing doesn’t work at all when the are more that two enabled cameras.

In a 4 player split screen game, I would like to be able to apply different post processing effects for each screen, would you have any recommendation to bypass or fix the post-processing stack limitation ?
