### ISSUE TITLE
Motion Vectors getting rendered even if Motion Blur is disabled

### ISSUE THREAD

**Issue by spaceemotion** [Unity-Technologies/PostProcessing#66]
In our game we do not need the motion vectors, and usually have less than 100 batches maximum. With the stack enabled (we only use TAA, Grain and the Vignette) we get about 400-500 batches, which is sometimes 10x more than usual.

I don't know if this is the intended behaviour, but is there a way to stop this?

**Comment by gokselgoktas** [comment]
Temporal Anti-aliasing is a technique that requires motion vectors in order to reproject the samples from its history buffer to the current frame's fragment coordinates. In fact motion vectors do have way more uses than merely a motion blur. 😊

Therefore this indeed is the intended behavior, and the only way to stop it would be to disable every effect requiring the use of motion vectors; in this case TAA.
