### ISSUE TITLE
How to modify brightness in runtime via script?

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#73]
I find Channel Mixer can used to do that, but there is a easier way?

**Comment by Chman** [comment]
The `Post Exposure` setting is what you're looking for. Also, see #11.

**Comment by silentlamb1991** [comment]
I tried Post Exposure, I'm not sure what EV always means black screen? It's a fixed value or relatived to screen picture?

**Comment by silentlamb1991** [comment]
I tried -10 the screen is totally black, then I change the emission brightness of a material from 1.5 to 4, the screen is not totally black now. I hope there is a brightness value in range [0, 1], 0 means black and 1 means normal.

**Comment by Chman** [comment]
If you're trying to do a fade from/to black you can use a black alpha plane instead of trying to leverage the full color grading pipeline.

EV is an exposure value unit (the same you got on your camera). It's an exponential value (`exp2`). There's no brightness multiplier setting in the stack and we have no plan to add one at this point.
