### ISSUE TITLE
DOF shows a strange line

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#76]
![default](https://cloud.githubusercontent.com/assets/18855621/22173244/c75d2d70-dff7-11e6-953d-12edee6a88e4.PNG)

**Comment by Kink3d** [comment]
Hi,

This should be fixed by this experimental branch (pre-dilate and recalculate CoC disabled): https://github.com/keijiro/PostProcessing/commit/db1c48ffb871a4e1e7361d10243b11c82e03f8b1

We are currently looking at performances, regressions and impacts with related issues #40 and #26 before merging this branch to master.

Thanks

**Comment by Kink3d** [comment]
Closing as #26 also contains this exact problem.
