### ISSUE TITLE
User LUT compression in OSX/Metal

### ISSUE THREAD

**Issue by JacobSmaga** [Unity-Technologies/PostProcessing#86]
![image](https://cloud.githubusercontent.com/assets/11807714/22622141/0cdbb880-eb33-11e6-812a-8f2b691de46f.png)

**Comment by lumpex999** [comment]
Unity 5.6.0b6/Newest stack from Github

**Comment by JacobSmaga** [comment]
It's only happening in build

**Comment by Chman** [comment]
This seems to be an issue with quality settings & Metal. If you go to `Quality Settings` and change `Anisotropic Textures` to `Per Texture` instead of `Forced On` that should fix it. I've reported the bug internally as `Forced On` shouldn't force anisotropic filtering on texture where it's explicitly disabled.

**Comment by Kink3d** [comment]
For reference here is the internal bug ticket: [https://fogbugz.unity3d.com/f/cases/881055/](url)

Will close this now just to clean up issues list a bit.
