### ISSUE TITLE
Not working in 2019.3.0f1

### ISSUE THREAD

**Issue by Sphelex** [Unity-Technologies/PostProcessing#868]
##### What happened?
Converted my project from 2019.2.8f1 to 2019.3.0f1 and post processing is not working, no idea why.
Tried removing package and then adding it again, reimported project, no luck.
Scripts are there but when i try to change something, like vibrance, nothing changes
##### Post-processing stack version (v1, v2)?
v2.2.2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2019.3.0f1, Windows 10 64-bit, windows

**Comment by amartinez1660** [comment]
You have to use 
- "Volume" script instead of the Post Process Volume
- "Volume Profiles" instead of Post Process Profiles
- Activate Post Process on the camera, instead of using a "Post Process Layer"
- Recreate all your post processing effects from Post Stack using the "new" ones (they are mostly the same but with less features and sometimes a tad different behaviour, they are also split a bit more -> color grading is now a series of LiftGammaGain/WhiteBalance/etc which is both nice and bad).
- Can't create custom post process effects (hopefully a temporal thing).

**Comment by Sphelex** [comment]
> You have to use
> 
> * "Volume" script instead of the Post Process Volume
> * "Volume Profiles" instead of Post Process Profiles
> * Activate Post Process on the camera, instead of using a "Post Process Layer"
> * Recreate all your post processing effects from Post Stack using the "new" ones (they are mostly the same but with less features and sometimes a tad different behaviour, they are also split a bit more -> color grading is now a series of LiftGammaGain/WhiteBalance/etc which is both nice and bad).
> * Can't create custom post process effects (hopefully a temporal thing).

That fixed it, thanks!
