### ISSUE TITLE
AO of terrain's trees overlaps in front the objects

### ISSUE THREAD

**Issue by sardinax** [Unity-Technologies/PostProcessing#89]
Thanks for this great job!

This issue only happens when I uncheck "ambient only" option from AO. 

Camera is in deferred path, realtime GI precomputed and baked GI.

Trees are imported from Unity enviroment package.

![image](https://cloud.githubusercontent.com/assets/421079/22781799/80b3a68e-eec4-11e6-8304-49dd68470857.png)

Thanks in advance

**Comment by Kink3d** [comment]
Hi,

It appears that you have a render order issue. Could you send a reproduction project so we can help you figure it out?

Thanks

**Comment by sardinax** [comment]
Yes,

I realised that problem comes when I have the "Baked GI" lighting option checked and directional light in mixed mode (with deferred path). I don't know if this config is wrong.

To make the attatch file lighter I removed Effects, Enviroment and Postprocessing packages from zip, reimport them to test it.
[AOProblem.zip](https://github.com/Unity-Technologies/PostProcessing/files/787411/AOProblem.zip)


Thanks in advance!

**Comment by Kink3d** [comment]
Ok so the problem here is the standard terrain shader renders in forward (I have no idea why) so its not being taken into account when rendering the AO. If you set the terrain to use a custom material you'll see that it fixes your issue. 

However the regular Standard shader is not suitable for terrain rendering (for many reasons) so your options are:

1) Write/use a custom terrain shader that renders in deferred
2) Enable "Force forward compatibility" on SSAO

I've checked both and confirm they fix your issue.

(ps. The rocks which aren't in the reproduction project appear to also be rendering in forward)

**Comment by sardinax** [comment]
Thanks for your answer,

I think that it works, but when I check "Force Forward Compatibility", appears this only on trees in "contact" with skybox:
![image](https://cloud.githubusercontent.com/assets/421079/23176693/7b2e91f2-f864-11e6-8f26-cead76301406.png)
![image](https://cloud.githubusercontent.com/assets/421079/23176884/3054333e-f865-11e6-9a98-b4c6037c4532.png)


but I don't think that it is a postprocessing issue... when I put light in baked mode it disappears but also disappears all shadows.

Thanks again!
