### ISSUE TITLE
Dof parameters cause strange behaviour

### ISSUE THREAD

**Issue by ghiboz** [Unity-Technologies/PostProcessing#92]
hi all!
i'm trying to use your DOF, with 'real' parameters and in the example: using f/1.6 a focal length of 105mm and the object of a distance of 15meters, the scene is too much focused, in the real life, a dof with a 1.6 at 105 mm is too small

![grallysim_2017-02-10-15-14-07](https://cloud.githubusercontent.com/assets/446533/22829698/21e3fb32-efa4-11e6-8364-300131287d19.png)

in my calcs, the camera has a field of view of 13.1°

the calcs are due with a code like this:
http://www.howardedin.com/articles/fov.html
![](http://i.imgur.com/6bxwoBZ.png)

**Comment by Kink3d** [comment]
Hi,

Sorry for the late reply. You're right, but after a fair amount of looking into this it seems like this is just due to the limitations of Unity's current camera situation. As the camera is just a render target and not an actual camera real parameters for camera effects like DoF just wont work.

So I'm afraid there's not much we can do here right now. Ill close the issue but you can open it up again if you want to discuss this further.
