### ISSUE TITLE
TAA flicker when faces too close

### ISSUE THREAD

**Issue by cakeslice** [Unity-Technologies/PostProcessing#98]
Hi, I noticed some flickering in an archviz animation when using TAA so I tried to reproduce it and here it is:

Video of the problem: https://gfycat.com/DeadDismalAcornweevil

Project: https://www.dropbox.com/s/2fukpy1d2dhkbwz/TAAbug.zip?dl=0

I know depth issues are expected when you put faces too close to each other but TAA is way too sensitive.

**Comment by Chman** [comment]
Thanks for the repro-case, that's very appreciated !

Regarding the issue itself: TAA isn't too sensitive. The issue comes from the fact that for TAA to work Unity needs to jitter the camera projection matrix on every frame (which essentially moves the camera a tiny bit and messes with the focal length). If I disable TAA but keep the jittering I'll see the same issue, and it looks even worse because there isn't any TAA trying to smooth it out. If I drop down the jitter spread in TAA it does fix the issue in this specific scene.

It's by design. It's definitely a z-fighting issue and you can fix it by either lowering the jitter spread value or fixing it like any other z-fighting issue: move the object a bit further away from the surface or use a narrower field of view.
